-- content_catalog.sql — generated; do not edit by hand
-- Source: public/arena + src/content

CREATE TABLE IF NOT EXISTS public.arena_catalog (
  lang TEXT NOT NULL,
  season_id INTEGER NOT NULL,
  level_id INTEGER NOT NULL,
  PRIMARY KEY (lang, season_id, level_id)
);
ALTER TABLE public.arena_catalog ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read arena catalog" ON public.arena_catalog;
CREATE POLICY "Anyone can read arena catalog" ON public.arena_catalog FOR SELECT USING (true);
TRUNCATE public.arena_catalog;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 2) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 3) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 4) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 5) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 6) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 7) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 8) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 9) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 10) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 11) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 12) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 13) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 14) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 16) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 17) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 18) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 19) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 20) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 21) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 22) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 23) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 24) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 25) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 26) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 27) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 28) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 29) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 30) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 31) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 32) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 1, 33) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 2, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.arena_catalog (lang, season_id, level_id) VALUES ('nl', 2, 2) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.learning_content (
  kind TEXT NOT NULL CHECK (kind IN ('grammar_lesson','test_passed','vocabulary_word','exercise_correct')),
  content_id TEXT NOT NULL,
  PRIMARY KEY (kind, content_id)
);
ALTER TABLE public.learning_content ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read learning content" ON public.learning_content;
CREATE POLICY "Anyone can read learning content" ON public.learning_content FOR SELECT USING (true);
TRUNCATE public.learning_content;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'a2SpeedrunCheatSheet') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'aanHetInVoltooideTijden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'aaneenschrijvenOfLos') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'aanvoegendeWijs') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'aanwijzendeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'accenttekens') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'afkortingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'afsprakenMaken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'beknopteBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'belangrijkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'beleefdheidsverzoekenZou') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'betrekkelijkVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bezittelijkeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijvoeglijkNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijvoeglijkeBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijwoordelijkeBepaling') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijwoordenFrequentieGraad') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'bijzinSov') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'boodschappen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'breukenGetallen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'cafe') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'cijfersGetallen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'congruentie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'discussiesVoeren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'familie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'feestdagen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'focuspartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'formeelEnInformeel') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'formulieren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gebiedendeWijs') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gebiedendeWijsPartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gebiedendeZinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gereduceerdevormen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gevoelensEnMeningen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'gevoelensEnNuance') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'groeten') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hebbenZijnZullen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hetWoordEr') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hoofdletters') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hoofdtelwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hoofdzinMededelend') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'hulpwerkwoordKeuze') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'indirecteRede') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'infinitiefMetTe') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'infinitiefStamIkvorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'ingebeddeVragen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'inversieHoofdzin') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'kaleInfinitief') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'kleineletters') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'kleuren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'koppelteken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'koppelwerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'leestekens') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'leesvaardigheid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'leesvaardigheidAdvertenties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'leesvaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'lidwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'lijdendVoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'lijdendeVorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'luisterenStation') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'luistervaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'meervoud') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'meewerkendVoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'modalePartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'modaleWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'naamwoordelijkGezegde') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'nevenschikkendeVoegwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onbepaaldeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onderschikkendeVoegwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onderwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onpersoonlijkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onscheidbareWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'ontkenningGeen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'ontkenningNiet') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onvoltooidDeelwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'onvoltooidVerledenToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'otttZullen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'ovt') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'partikelCombinaties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'partitieveS') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'passiefAlleTijden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'persoonlijkeVoornaamwoordenObject') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'persoonlijkeVoornaamwoordenOnderwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'persoonsvorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'progressiefconstructies') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'rangtelwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'routines') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'scheidbareWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'schrijfvaardigheidBericht') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'schrijfvaardigheidBriefVerslag') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'schrijfvaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'solliciteren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'soortenBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'spreekvaardigheid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'spreekvaardigheidVoorstellen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'stapelwerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'sterkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'stijlfoutenTautologiePleonasme') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'tKofschip') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'tangconstructie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'tegenwoordigeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'telbaarNietTelbaarNominalisatie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'telefonerenOfficieleInstanties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'trappenVanVergelijking') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'tremaApostrof') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'tussenklanken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'uitroependVoornaamwoord2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'uitspraak') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vasteVoorzetselcombinaties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'verbaleStijl') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'verwarrendeWerkwoordparen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'verwijswoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'volgordeBijwoordelijkeBepalingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voltooidDeelwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voltooidDeelwoordAlsBijvoeglijkNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voltooidToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voltooidVerledenTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voltooidVerledenToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voornaamwoordelijkBijwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vooropplaatsing') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voorstellen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voorzetsels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voorzetselsTijdPlaatsUitgebreid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'voorzetselvoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vraagzinnenMetPartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vraagzinnenVraagwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vraagzinnenjanee') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vragendVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'vtt') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'wederkerendVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'wederkerendeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'wederkerigVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'wegVragen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'werkwoordelijkGezegde') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'werkwoordelijkeUitdrukkingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'zelfevaluatieA1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'zelfstandigBezittelijkVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'zelfstandigNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'zinssymbolen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('grammar_lesson', 'zinsverzachtendMaar') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'de') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'en') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'es') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'fr') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'werkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('test_passed', 'nl/werkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-3') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-4') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-5') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-6') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-7') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-8') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-9') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-10') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-11') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-12') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-13') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-14') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'de-w-15') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-3') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-4') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-5') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-6') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-7') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-8') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-9') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-10') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-11') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-12') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-13') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-14') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'en-w-15') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-3') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-4') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-5') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-6') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-7') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-8') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-9') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-10') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-11') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-12') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-13') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-14') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'es-w-15') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-3') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-4') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-5') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-6') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-7') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-8') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-9') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-10') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-11') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-12') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-13') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-14') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'fr-w-15') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-3') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-4') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-5') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-6') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-7') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-8') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-9') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-10') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-11') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-12') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-13') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-14') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('vocabulary_word', 'nl-w-15') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:a2SpeedrunCheatSheet') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:aanHetInVoltooideTijden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:aaneenschrijvenOfLos') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:aanvoegendeWijs') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:aanwijzendeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:accenttekens') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:afkortingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:afsprakenMaken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:beknopteBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:belangrijkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:beleefdheidsverzoekenZou') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:betrekkelijkVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bezittelijkeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijvoeglijkNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijvoeglijkeBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijwoordelijkeBepaling') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijwoordenFrequentieGraad') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:bijzinSov') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:boodschappen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:breukenGetallen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:cafe') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:cijfersGetallen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:congruentie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:discussiesVoeren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:familie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:feestdagen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:focuspartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:formeelEnInformeel') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:formulieren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gebiedendeWijs') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gebiedendeWijsPartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gebiedendeZinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gereduceerdevormen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gevoelensEnMeningen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:gevoelensEnNuance') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:groeten') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hebbenZijnZullen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hetWoordEr') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hoofdletters') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hoofdtelwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hoofdzinMededelend') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:hulpwerkwoordKeuze') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:indirecteRede') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:infinitiefMetTe') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:infinitiefStamIkvorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:ingebeddeVragen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:inversieHoofdzin') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:kaleInfinitief') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:kleineletters') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:kleuren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:koppelteken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:koppelwerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:lazyIndex') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:leestekens') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:leesvaardigheid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:leesvaardigheidAdvertenties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:leesvaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:lidwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:lijdendVoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:lijdendeVorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:luisterenStation') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:luistervaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:meervoud') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:meewerkendVoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:modalePartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:modaleWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:naamwoordelijkGezegde') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:nevenschikkendeVoegwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onbepaaldeVoornaamwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onderschikkendeVoegwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onderwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onpersoonlijkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onscheidbareWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:ontkenningGeen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:ontkenningNiet') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onvoltooidDeelwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:onvoltooidVerledenToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:otttZullen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:ovt') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:partikelCombinaties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:partitieveS') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:passiefAlleTijden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:persoonlijkeVoornaamwoordenObject') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:persoonlijkeVoornaamwoordenOnderwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:persoonsvorm') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:progressiefconstructies') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:rangtelwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:routines') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:scheidbareWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:schrijfvaardigheidBericht') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:schrijfvaardigheidBriefVerslag') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:schrijfvaardigheidC1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:solliciteren') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:soortenBijzinnen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:spreekvaardigheid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:spreekvaardigheidVoorstellen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:stapelwerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:sterkeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:stijlfoutenTautologiePleonasme') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:tKofschip') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:tangconstructie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:tegenwoordigeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:telbaarNietTelbaarNominalisatie') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:telefonerenOfficieleInstanties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:trappenVanVergelijking') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:tremaApostrof') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:tussenklanken') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:uitroependVoornaamwoord2') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:uitspraak') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vasteVoorzetselcombinaties') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:verbaleStijl') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:verwarrendeWerkwoordparen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:verwijswoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:volgordeBijwoordelijkeBepalingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voltooidDeelwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voltooidDeelwoordAlsBijvoeglijkNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voltooidToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voltooidVerledenTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voltooidVerledenToekomendeTijd') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voornaamwoordelijkBijwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vooropplaatsing') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voorstellen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voorzetsels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voorzetselsTijdPlaatsUitgebreid') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:voorzetselvoorwerp') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vraagzinnenMetPartikels') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vraagzinnenVraagwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vraagzinnenjanee') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vragendVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:vtt') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:wederkerendVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:wederkerendeWerkwoorden') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:wederkerigVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:wegVragen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:werkwoordelijkGezegde') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:werkwoordelijkeUitdrukkingen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:zelfevaluatieA1') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:zelfstandigBezittelijkVoornaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:zelfstandigNaamwoord') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:zinssymbolen') ON CONFLICT DO NOTHING;
INSERT INTO public.learning_content (kind, content_id) VALUES ('exercise_correct', 'exercise:zinsverzachtendMaar') ON CONFLICT DO NOTHING;
