export type UILanguage = "en" | "nl" | "fr" | "de" | "es";
export const UI_LANGUAGES: { code: UILanguage; name: string; flag: string }[] = [
  { code: "en", name: "English", flag: "🇬🇧" }, { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "fr", name: "Français", flag: "🇫🇷" }, { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Español", flag: "🇪🇸" },
];

type Dict = Record<string, string>;
const en: Dict = {
  // TopBar
  "topbar.level":"Level","topbar.xp":"XP","topbar.logout":"Log out","topbar.streak":"day streak","topbar.uiLanguage":"Interface language",
  // Login
  "login.title":"Welcome back","login.subtitle":"Log in to continue","login.identifier":"Username or Email","login.password":"Password","login.forgotPassword":"Forgot password?","login.rememberMe":"Remember me","login.submit":"Log in","login.noAccount":"Don't have an account?","login.createAccount":"Create one","login.errorEmpty":"Please fill in all fields.","login.errorInvalid":"Invalid credentials.","login.errorGeneral":"Something went wrong.","login.forgotMsg":"Please create a new account if you forgot your password.",
  // Register
  "register.title":"Create your account","register.subtitle":"Start learning today","register.email":"Email","register.username":"Username","register.password":"Password","register.confirmPassword":"Confirm Password","register.submit":"Register","register.hasAccount":"Already have an account?","register.loginLink":"Log in","register.errorEmailRequired":"Email is required.","register.errorEmailFormat":"Please enter a valid email.","register.errorUsernameRequired":"Username is required.","register.errorUsernameShort":"Username must be at least 3 characters.","register.errorUsernameChars":"Only letters, numbers and underscores.","register.errorPasswordRequired":"Password is required.","register.errorPasswordShort":"Password must be at least 6 characters.","register.errorConfirmRequired":"Please confirm your password.","register.errorConfirmMatch":"Passwords do not match.","register.errorEmailExists":"An account with this email already exists.","register.errorUsernameTaken":"This username is already taken.",
  // Dashboard
  "dashboard.welcome":"Welcome back,","dashboard.noLanguagePrompt":"Pick a language below to start learning!","dashboard.learningLanguage":"Learning","dashboard.level":"Level","dashboard.totalXP":"Total XP","dashboard.streak":"Streak","dashboard.days":"days","dashboard.language":"Language","dashboard.none":"None","dashboard.xpProgress":"Progress to Level","dashboard.needMoreXP":"You need","dashboard.moreXP":"more XP to reach Level","dashboard.dailyGoal":"Today's Goal","dashboard.dailyGoalReached":"Goal reached! Great job!","dashboard.dailyGoalEmpty":"Do a quick exercise to get started!","dashboard.continueLearning":"Continue Learning","dashboard.chooseLanguage":"Choose your language","dashboard.streakActive":"day streak! Keep going!","dashboard.streakAtRisk":"Don't lose your streak!","dashboard.emptyStreak":"Start your streak today!",
  // Language names
  "lang.en":"English","lang.nl":"Dutch","lang.fr":"French","lang.de":"German","lang.es":"Spanish",
  // WOTD
  "wotd.title":"Word of the Day","wotd.i_know":"I Know This","wotd.show_hint":"Need a hint?","wotd.dont_know":"I Don't Know","wotd.learned":"Learned!","wotd.back_tomorrow":"Come back tomorrow for your next word","wotd.all_done":"All Done for Today!","wotd.all_done_msg":"You've already practiced today.","wotd.review":"Review Words","wotd.words_learned":"words learned","wotd.youre_done":"You're Done for Today","wotd.see_tomorrow":"See you tomorrow!",
  // Grammar
  "grammar.title":"Grammar Lessons","grammar.back_lessons":"Back to Lessons","grammar.learn":"Learn","grammar.test":"Test","grammar.test_coming":"Test coming soon","grammar.mark_complete":"Mark as Complete","grammar.completed":"Completed","grammar.search":"Search lessons...","grammar.no_match":"No lessons match.","grammar.exercises_title":"Quick Exercises",
  "grammar.overview":"What you'll learn","grammar.build":"What you can build","grammar.conjugation":"Conjugation","grammar.rules":"Grammar rules","grammar.time_expr":"Time expressions","grammar.details":"Detailed explanation","grammar.callouts":"Important points","grammar.mistakes_title":"Common mistakes","grammar.review":"Quick review","grammar.qa":"Practice questions",
  // Vocabulary
  "vocab.title":"Vocabulary","vocab.back":"Back to Vocabulary","vocab.mark_learned":"Mark as Learned","vocab.learned":"Learned","vocab.search":"Search words...","vocab.example":"Example","vocab.progress":"learned",
  // Tests
  "tests.title":"Tests & Quizzes","tests.back":"Back to Tests","tests.search":"Search tests...","tests.pass":"Pass","tests.questions":"questions","tests.passed":"Test Passed!","tests.keep_practicing":"Keep Practicing!","tests.score":"Score","tests.xp_earned":"XP Earned","tests.submit":"Submit Test","tests.previous":"Previous","tests.next":"Next",
  // Exercise
  "exercise.title":"Practice Mode","exercise.subtitle":"Pick a topic and answer questions.","exercise.all_topics":"All Topics","exercise.correct":"Correct!","exercise.wrong":"Not quite. Correct answer:","exercise.no_penalty":"No XP penalty — keep going!","exercise.next_question":"Next Question","exercise.see_results":"See Results","exercise.new_session":"New Session","exercise.complete":"Practice Complete!","exercise.accuracy":"accuracy","exercise.earned":"XP earned",
  // Mistakes
  "mistakes.title":"Mistake Review","mistakes.subtitle":"Learn from your mistakes","mistakes.search":"Search mistakes...","mistakes.no_mistakes":"No mistakes yet!","mistakes.no_mistakes_msg":"Mistakes will appear here.","mistakes.no_match":"No matches","mistakes.total":"Total","mistakes.unreviewed":"Unreviewed","mistakes.reviewed":"Reviewed","mistakes.review":"Mark as Reviewed","mistakes.delete":"Delete","mistakes.clear_all":"Clear all","mistakes.question":"Question","mistakes.your_answer":"Your Answer","mistakes.correct_answer":"Correct Answer","mistakes.practice_again":"Practice Again","mistakes.source_exercise":"Practice","mistakes.source_test":"Test",
  // AI
  "ai.title":"AI Tutor","ai.premium_ul":"Premium — unlimited","ai.paywall":"Payment required","ai.unlock_btn":"Unlock for €3 via PayPal","ai.unlock_title":"Unlock AI Tutor","ai.unlock_desc":"Get unlimited AI grammar, translations, and conversation.","ai.grammar_feat":"Grammar explanations","ai.translate_feat":"Translate anything","ai.convo_feat":"Conversation practice","ai.claude_feat":"Powered by Claude AI","ai.grammar_mode":"Grammar Help","ai.translate_mode":"Translation","ai.convo_mode":"Conversation","ai.grammar_desc":"Ask about any grammar rule","ai.translate_desc":"Translate phrases & sentences","ai.convo_desc":"Practice speaking naturally","ai.powered_by":"powered by Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Secure PayPal",
  // Profile
  "profile.member_since":"Member since","profile.learning_langs":"Learning Languages","profile.currently_learning":"Currently learning","profile.earned":"Earned!","profile.membership":"Membership","profile.premium_member":"Premium Member","profile.free_plan":"Free Plan","profile.manage":"Manage","profile.upgrade":"Upgrade","profile.this_week":"This Week","profile.days_active":"of 7 days active",
  // Settings
  "settings.title":"Settings","settings.account":"Account","settings.preferences":"Preferences","settings.learning":"Learning","settings.ai_tab":"AI","settings.change_email":"Change Email","settings.change_password":"Change Password","settings.delete_account":"Delete Account","settings.theme":"Theme","settings.light":"Light","settings.dark":"Dark","settings.ui_language":"Interface Language","settings.learning_lang":"Learning Language","settings.reset_progress":"Reset Progress","settings.daily_goal":"Daily XP Goal",
  // Nav
  "nav.home":"Home","nav.grammar":"Grammar","nav.words":"Words","nav.tests":"Tests","nav.practice":"Practice","nav.mistakes":"Mistakes","nav.ai_chat":"AI Chat",
  // Generic
  "generic.back_dashboard":"Back to Dashboard","generic.cancel":"Cancel","generic.save":"Save","generic.loading":"Loading...",
  // Misc
  "placeholder.email":"you@example.com","placeholder.username":"username","placeholder.password":"Min. 6 characters","placeholder.confirmPassword":"Re-enter password","placeholder.identifier":"username or email","placeholder.passwordLogin":"Enter password",
};
const nl: Dict = {
  "topbar.level":"Niveau","topbar.xp":"EP","topbar.logout":"Uitloggen","topbar.streak":"dagen streak","topbar.uiLanguage":"Interface taal",
  "login.title":"Welkom terug","login.subtitle":"Log in om verder te leren","login.identifier":"Gebruikersnaam of e-mail","login.password":"Wachtwoord","login.forgotPassword":"Wachtwoord vergeten?","login.rememberMe":"Onthoud mij","login.submit":"Inloggen","login.noAccount":"Nog geen account?","login.createAccount":"Account aanmaken","login.errorEmpty":"Vul alle velden in.","login.errorInvalid":"Ongeldige inloggegevens.","login.errorGeneral":"Er is iets misgegaan.","login.forgotMsg":"Maak een nieuw account aan als u uw wachtwoord bent vergeten.",
  "register.title":"Account aanmaken","register.subtitle":"Begin vandaag met leren","register.email":"E-mail","register.username":"Gebruikersnaam","register.password":"Wachtwoord","register.confirmPassword":"Bevestig wachtwoord","register.submit":"Registreren","register.hasAccount":"Heb je al een account?","register.loginLink":"Inloggen","register.errorEmailRequired":"E-mail is verplicht.","register.errorEmailFormat":"Voer een geldig e-mailadres in.","register.errorUsernameRequired":"Gebruikersnaam is verplicht.","register.errorUsernameShort":"Minimaal 3 tekens.","register.errorUsernameChars":"Alleen letters, cijfers en underscores.","register.errorPasswordRequired":"Wachtwoord is verplicht.","register.errorPasswordShort":"Minimaal 6 tekens.","register.errorConfirmRequired":"Bevestig je wachtwoord.","register.errorConfirmMatch":"Wachtwoorden komen niet overeen.","register.errorEmailExists":"Dit e-mailadres bestaat al.","register.errorUsernameTaken":"Deze gebruikersnaam is al in gebruik.",
  "dashboard.welcome":"Welkom terug,","dashboard.noLanguagePrompt":"Kies een taal om te beginnen!","dashboard.learningLanguage":"Leren","dashboard.level":"Niveau","dashboard.totalXP":"Totale EP","dashboard.streak":"Streak","dashboard.days":"dagen","dashboard.language":"Taal","dashboard.none":"Geen","dashboard.xpProgress":"Voortgang naar Niveau","dashboard.needMoreXP":"Je hebt nog","dashboard.moreXP":"EP nodig voor Niveau","dashboard.dailyGoal":"Doel van Vandaag","dashboard.dailyGoalReached":"Doel behaald! Goed gedaan!","dashboard.dailyGoalEmpty":"Doe een snelle oefening!","dashboard.continueLearning":"Verder Leren","dashboard.chooseLanguage":"Kies je taal","dashboard.streakActive":"dagen streak! Ga door!","dashboard.streakAtRisk":"Verlies je streak niet!","dashboard.emptyStreak":"Begin je streak vandaag!",
  "lang.en":"Engels","lang.nl":"Nederlands","lang.fr":"Frans","lang.de":"Duits","lang.es":"Spaans",
  "wotd.title":"Woord van de Dag","wotd.i_know":"Ik Ken Het","wotd.show_hint":"Hint nodig?","wotd.dont_know":"Ik Ken Het Niet","wotd.learned":"Geleerd!","wotd.back_tomorrow":"Kom morgen terug","wotd.all_done":"Klaar voor Vandaag!","wotd.all_done_msg":"Je hebt vandaag al geoefend.","wotd.review":"Herhaal Woorden","wotd.words_learned":"woorden geleerd","wotd.youre_done":"Klaar voor Vandaag","wotd.see_tomorrow":"Tot morgen!",
  "grammar.title":"Grammatica Lessen","grammar.back_lessons":"Terug naar Lessen","grammar.learn":"Leren","grammar.test":"Toets","grammar.test_coming":"Toets volgt","grammar.mark_complete":"Markeer als Voltooid","grammar.completed":"Voltooid","grammar.search":"Lessen zoeken...","grammar.no_match":"Geen lessen gevonden.","grammar.exercises_title":"Snelle Oefeningen",
  "grammar.overview":"Wat ga je leren","grammar.build":"Wat je kunt bouwen","grammar.conjugation":"Vervoeging","grammar.rules":"Grammaticaregels","grammar.time_expr":"Tijdsuitdrukkingen","grammar.details":"Gedetailleerde uitleg","grammar.callouts":"Belangrijke punten","grammar.mistakes_title":"Veelgemaakte fouten","grammar.review":"Snelle herhaling","grammar.qa":"Oefenvragen",
  "vocab.title":"Woordenschat","vocab.back":"Terug naar Woorden","vocab.mark_learned":"Markeer als Geleerd","vocab.learned":"Geleerd","vocab.search":"Woorden zoeken...","vocab.example":"Voorbeeld","vocab.progress":"geleerd",
  "tests.title":"Toetsen & Quizzen","tests.back":"Terug naar Toetsen","tests.search":"Toetsen zoeken...","tests.pass":"Slaag","tests.questions":"vragen","tests.passed":"Geslaagd!","tests.keep_practicing":"Blijf Oefenen!","tests.score":"Score","tests.xp_earned":"EP Verdiend","tests.submit":"Toets Inleveren","tests.previous":"Vorige","tests.next":"Volgende",
  "exercise.title":"Oefenmodus","exercise.subtitle":"Kies een onderwerp en beantwoord vragen.","exercise.all_topics":"Alle Onderwerpen","exercise.correct":"Correct!","exercise.wrong":"Niet goed. Correct antwoord:","exercise.no_penalty":"Geen EP straf — ga door!","exercise.next_question":"Volgende Vraag","exercise.see_results":"Zie Resultaten","exercise.new_session":"Nieuwe Sessie","exercise.complete":"Oefening Voltooid!","exercise.accuracy":"nauwkeurigheid","exercise.earned":"EP verdiend",
  "mistakes.title":"Fout Review","mistakes.subtitle":"Leer van je fouten","mistakes.search":"Fouten zoeken...","mistakes.no_mistakes":"Nog geen fouten!","mistakes.no_mistakes_msg":"Fouten verschijnen hier.","mistakes.no_match":"Geen resultaten","mistakes.total":"Totaal","mistakes.unreviewed":"Onbekeken","mistakes.reviewed":"Bekeken","mistakes.review":"Markeer als Bekeken","mistakes.delete":"Verwijder","mistakes.clear_all":"Alles wissen","mistakes.question":"Vraag","mistakes.your_answer":"Jouw Antwoord","mistakes.correct_answer":"Juiste Antwoord","mistakes.practice_again":"Opnieuw Oefenen","mistakes.source_exercise":"Oefening","mistakes.source_test":"Toets",
  "ai.title":"AI Tutor","ai.premium_ul":"Premium — onbeperkt","ai.paywall":"Betaling nodig","ai.unlock_btn":"Ontgrendel voor €3 via PayPal","ai.unlock_title":"AI Tutor Ontgrendelen","ai.unlock_desc":"Onbeperkte AI grammatica, vertalingen en conversatie.","ai.grammar_feat":"Grammatica uitleg","ai.translate_feat":"Alles vertalen","ai.convo_feat":"Conversatie oefenen","ai.claude_feat":"Aangedreven door Claude AI","ai.grammar_mode":"Grammatica Hulp","ai.translate_mode":"Vertaling","ai.convo_mode":"Conversatie","ai.grammar_desc":"Vraag over grammatica regels","ai.translate_desc":"Vertaal zinnen","ai.convo_desc":"Oefen natuurlijk spreken","ai.powered_by":"aangedreven door Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Veilige PayPal",
  "profile.member_since":"Lid sinds","profile.learning_langs":"Talen Leren","profile.currently_learning":"Nu aan het leren","profile.earned":"Verdiend!","profile.membership":"Lidmaatschap","profile.premium_member":"Premium Lid","profile.free_plan":"Gratis Plan","profile.manage":"Beheer","profile.upgrade":"Upgrade","profile.this_week":"Deze Week","profile.days_active":"van 7 dagen actief",
  "settings.title":"Instellingen","settings.account":"Account","settings.preferences":"Voorkeuren","settings.learning":"Leren","settings.ai_tab":"AI","settings.change_email":"E-mail Wijzigen","settings.change_password":"Wachtwoord Wijzigen","settings.delete_account":"Account Verwijderen","settings.theme":"Thema","settings.light":"Licht","settings.dark":"Donker","settings.ui_language":"Interface Taal","settings.learning_lang":"Leer Taal","settings.reset_progress":"Voortgang Resetten","settings.daily_goal":"Dagelijks EP Doel",
  "nav.home":"Home","nav.grammar":"Grammatica","nav.words":"Woorden","nav.tests":"Toetsen","nav.practice":"Oefenen","nav.mistakes":"Fouten","nav.ai_chat":"AI Chat",
  "generic.back_dashboard":"Terug naar Dashboard","generic.cancel":"Annuleren","generic.save":"Opslaan","generic.loading":"Laden...",
  "placeholder.email":"jij@voorbeeld.nl","placeholder.username":"gebruikersnaam","placeholder.password":"Min. 6 tekens","placeholder.confirmPassword":"Voer wachtwoord opnieuw in","placeholder.identifier":"gebruikersnaam of email","placeholder.passwordLogin":"Voer wachtwoord in",
};
const fr: Dict = {
  "topbar.level":"Niveau","topbar.xp":"XP","topbar.logout":"Déconnexion","topbar.streak":"jours","topbar.uiLanguage":"Langue interface",
  "login.title":"Bon retour","login.subtitle":"Connectez-vous","login.identifier":"Nom d'utilisateur ou email","login.password":"Mot de passe","login.forgotPassword":"Mot de passe oublié?","login.rememberMe":"Se souvenir","login.submit":"Connexion","login.noAccount":"Pas de compte?","login.createAccount":"Créer un compte","login.errorEmpty":"Remplissez tous les champs.","login.errorInvalid":"Identifiants invalides.","login.errorGeneral":"Une erreur est survenue.","login.forgotMsg":"Créez un nouveau compte si vous avez oublié.",
  "register.title":"Créer un compte","register.subtitle":"Commencez à apprendre","register.email":"Email","register.username":"Nom d'utilisateur","register.password":"Mot de passe","register.confirmPassword":"Confirmer","register.submit":"S'inscrire","register.hasAccount":"Déjà un compte?","register.loginLink":"Connexion","register.errorEmailRequired":"Email requis.","register.errorEmailFormat":"Email invalide.","register.errorUsernameRequired":"Nom requis.","register.errorUsernameShort":"Min. 3 caractères.","register.errorUsernameChars":"Lettres, chiffres, underscores.","register.errorPasswordRequired":"Mot de passe requis.","register.errorPasswordShort":"Min. 6 caractères.","register.errorConfirmRequired":"Confirmez.","register.errorConfirmMatch":"Ne correspondent pas.","register.errorEmailExists":"Email déjà utilisé.","register.errorUsernameTaken":"Nom déjà pris.",
  "dashboard.welcome":"Bon retour,","dashboard.noLanguagePrompt":"Choisissez une langue!","dashboard.learningLanguage":"Apprentissage","dashboard.level":"Niveau","dashboard.totalXP":"XP Total","dashboard.streak":"Série","dashboard.days":"jours","dashboard.language":"Langue","dashboard.none":"Aucune","dashboard.xpProgress":"Progression","dashboard.needMoreXP":"Besoin de","dashboard.moreXP":"XP de plus","dashboard.dailyGoal":"Objectif du Jour","dashboard.dailyGoalReached":"Objectif atteint!","dashboard.dailyGoalEmpty":"Faites un exercice!","dashboard.continueLearning":"Continuer","dashboard.chooseLanguage":"Choisir langue","dashboard.streakActive":"jours! Continuez!","dashboard.streakAtRisk":"Ne perdez pas!","dashboard.emptyStreak":"Commencez aujourd'hui!",
  "lang.en":"Anglais","lang.nl":"Néerlandais","lang.fr":"Français","lang.de":"Allemand","lang.es":"Espagnol",
  "wotd.title":"Mot du Jour","wotd.i_know":"Je le sais","wotd.show_hint":"Un indice?","wotd.dont_know":"Je ne sais pas","wotd.learned":"Appris!","wotd.back_tomorrow":"Revenez demain","wotd.all_done":"Terminé!","wotd.all_done_msg":"Vous avez déjà pratiqué.","wotd.review":"Réviser","wotd.words_learned":"mots appris","wotd.youre_done":"Terminé","wotd.see_tomorrow":"À demain!",
  "grammar.title":"Leçons de Grammaire","grammar.back_lessons":"Retour","grammar.learn":"Apprendre","grammar.test":"Test","grammar.test_coming":"Test bientôt","grammar.mark_complete":"Marquer fini","grammar.completed":"Terminé","grammar.search":"Rechercher...","grammar.no_match":"Aucun résultat.","grammar.exercises_title":"Exercices Rapides",
  "grammar.overview":"Ce que tu vas apprendre","grammar.build":"Ce que tu peux construire","grammar.conjugation":"Conjugaison","grammar.rules":"Règles de grammaire","grammar.time_expr":"Expressions de temps","grammar.details":"Explication détaillée","grammar.callouts":"Points importants","grammar.mistakes_title":"Erreurs courantes","grammar.review":"Révision rapide","grammar.qa":"Questions pratiques",
  "vocab.title":"Vocabulaire","vocab.back":"Retour","vocab.mark_learned":"Marquer appris","vocab.learned":"Appris","vocab.search":"Rechercher...","vocab.example":"Exemple","vocab.progress":"appris",
  "tests.title":"Tests & Quiz","tests.back":"Retour","tests.search":"Rechercher...","tests.pass":"Réussite","tests.questions":"questions","tests.passed":"Réussi!","tests.keep_practicing":"Continuez!","tests.score":"Score","tests.xp_earned":"XP Gagné","tests.submit":"Soumettre","tests.previous":"Précédent","tests.next":"Suivant",
  "exercise.title":"Mode Pratique","exercise.subtitle":"Choisissez un sujet.","exercise.all_topics":"Tous","exercise.correct":"Correct!","exercise.wrong":"Incorrect. Réponse:","exercise.no_penalty":"Pas de pénalité!","exercise.next_question":"Suivante","exercise.see_results":"Résultats","exercise.new_session":"Nouvelle Session","exercise.complete":"Terminé!","exercise.accuracy":"précision","exercise.earned":"XP gagné",
  "mistakes.title":"Revue d'Erreurs","mistakes.subtitle":"Apprenez de vos erreurs","mistakes.search":"Rechercher...","mistakes.no_mistakes":"Pas d'erreurs!","mistakes.no_mistakes_msg":"Les erreurs apparaîtront ici.","mistakes.no_match":"Aucun","mistakes.total":"Total","mistakes.unreviewed":"Non vus","mistakes.reviewed":"Vus","mistakes.review":"Marquer vu","mistakes.delete":"Supprimer","mistakes.clear_all":"Tout effacer","mistakes.question":"Question","mistakes.your_answer":"Votre Réponse","mistakes.correct_answer":"Bonne Réponse","mistakes.practice_again":"Refaire","mistakes.source_exercise":"Exercice","mistakes.source_test":"Test",
  "ai.title":"Tuteur IA","ai.premium_ul":"Premium — illimité","ai.paywall":"Paiement requis","ai.unlock_btn":"Débloquer pour 3€","ai.unlock_title":"Débloquer Tuteur IA","ai.unlock_desc":"Grammaire, traductions, conversation illimitées.","ai.grammar_feat":"Explications grammaire","ai.translate_feat":"Tout traduire","ai.convo_feat":"Conversation","ai.claude_feat":"Par Claude AI","ai.grammar_mode":"Aide Grammaire","ai.translate_mode":"Traduction","ai.convo_mode":"Conversation","ai.grammar_desc":"Règles de grammaire","ai.translate_desc":"Traduire des phrases","ai.convo_desc":"Parler naturellement","ai.powered_by":"par Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"PayPal sécurisé",
  "profile.member_since":"Membre depuis","profile.learning_langs":"Langues","profile.currently_learning":"En cours","profile.earned":"Gagné!","profile.membership":"Abonnement","profile.premium_member":"Membre Premium","profile.free_plan":"Gratuit","profile.manage":"Gérer","profile.upgrade":"Upgrader","profile.this_week":"Cette Semaine","profile.days_active":"sur 7 jours",
  "settings.title":"Paramètres","settings.account":"Compte","settings.preferences":"Préférences","settings.learning":"Apprentissage","settings.ai_tab":"IA","settings.change_email":"Changer Email","settings.change_password":"Changer Mot de passe","settings.delete_account":"Supprimer Compte","settings.theme":"Thème","settings.light":"Clair","settings.dark":"Sombre","settings.ui_language":"Langue Interface","settings.learning_lang":"Langue Apprise","settings.reset_progress":"Réinitialiser","settings.daily_goal":"Objectif XP",
  "nav.home":"Accueil","nav.grammar":"Grammaire","nav.words":"Mots","nav.tests":"Tests","nav.practice":"Pratique","nav.mistakes":"Erreurs","nav.ai_chat":"IA Chat",
  "generic.back_dashboard":"Retour","generic.cancel":"Annuler","generic.save":"Sauver","generic.loading":"Chargement...",
  "placeholder.email":"vous@exemple.fr","placeholder.username":"nom","placeholder.password":"Min. 6","placeholder.confirmPassword":"Confirmer","placeholder.identifier":"nom ou email","placeholder.passwordLogin":"Mot de passe",
};
const de: Dict = {
  "topbar.level":"Level","topbar.xp":"EP","topbar.logout":"Abmelden","topbar.streak":"Tage","topbar.uiLanguage":"Oberfläche",
  "login.title":"Willkommen","login.subtitle":"Melde dich an","login.identifier":"Benutzername oder E-Mail","login.password":"Passwort","login.forgotPassword":"Passwort vergessen?","login.rememberMe":"Angemeldet bleiben","login.submit":"Anmelden","login.noAccount":"Kein Konto?","login.createAccount":"Erstellen","login.errorEmpty":"Alle Felder ausfüllen.","login.errorInvalid":"Ungültig.","login.errorGeneral":"Fehler.","login.forgotMsg":"Neues Konto erstellen.",
  "register.title":"Konto erstellen","register.subtitle":"Heute lernen","register.email":"E-Mail","register.username":"Benutzername","register.password":"Passwort","register.confirmPassword":"Bestätigen","register.submit":"Registrieren","register.hasAccount":"Schon Konto?","register.loginLink":"Anmelden","register.errorEmailRequired":"E-Mail nötig.","register.errorEmailFormat":"Gültige E-Mail.","register.errorUsernameRequired":"Name nötig.","register.errorUsernameShort":"Min. 3 Zeichen.","register.errorUsernameChars":"Nur Buchstaben/Zahlen.","register.errorPasswordRequired":"Passwort nötig.","register.errorPasswordShort":"Min. 6 Zeichen.","register.errorConfirmRequired":"Bestätigen.","register.errorConfirmMatch":"Stimmt nicht überein.","register.errorEmailExists":"E-Mail existiert.","register.errorUsernameTaken":"Name vergeben.",
  "dashboard.welcome":"Willkommen,","dashboard.noLanguagePrompt":"Wähle eine Sprache!","dashboard.learningLanguage":"Lernen","dashboard.level":"Level","dashboard.totalXP":"Gesamt-EP","dashboard.streak":"Streak","dashboard.days":"Tage","dashboard.language":"Sprache","dashboard.none":"Keine","dashboard.xpProgress":"Fortschritt","dashboard.needMoreXP":"Brauchst","dashboard.moreXP":"EP mehr","dashboard.dailyGoal":"Tagesziel","dashboard.dailyGoalReached":"Ziel erreicht!","dashboard.dailyGoalEmpty":"Mach eine Übung!","dashboard.continueLearning":"Weiterlernen","dashboard.chooseLanguage":"Wähle Sprache","dashboard.streakActive":"Tage! Weiter!","dashboard.streakAtRisk":"Nicht verlieren!","dashboard.emptyStreak":"Starte heute!",
  "lang.en":"Englisch","lang.nl":"Niederländisch","lang.fr":"Französisch","lang.de":"Deutsch","lang.es":"Spanisch",
  "wotd.title":"Wort des Tages","wotd.i_know":"Ich weiß es","wotd.show_hint":"Hinweis?","wotd.dont_know":"Weiß nicht","wotd.learned":"Gelernt!","wotd.back_tomorrow":"Morgen wiederkommen","wotd.all_done":"Fertig!","wotd.all_done_msg":"Heute schon geübt.","wotd.review":"Wiederholen","wotd.words_learned":"Wörter gelernt","wotd.youre_done":"Fertig","wotd.see_tomorrow":"Bis morgen!",
  "grammar.title":"Grammatik","grammar.back_lessons":"Zurück","grammar.learn":"Lernen","grammar.test":"Test","grammar.test_coming":"Test bald","grammar.mark_complete":"Abschließen","grammar.completed":"Abgeschlossen","grammar.search":"Suchen...","grammar.no_match":"Nichts gefunden.","grammar.exercises_title":"Übungen",
  "grammar.overview":"Was du lernst","grammar.build":"Was du bauen kannst","grammar.conjugation":"Konjugation","grammar.rules":"Grammatikregeln","grammar.time_expr":"Zeitausdrücke","grammar.details":"Detaillierte Erklärung","grammar.callouts":"Wichtige Punkte","grammar.mistakes_title":"Häufige Fehler","grammar.review":"Schnelle Wiederholung","grammar.qa":"Übungsfragen",
  "vocab.title":"Wortschatz","vocab.back":"Zurück","vocab.mark_learned":"Gelernt markieren","vocab.learned":"Gelernt","vocab.search":"Suchen...","vocab.example":"Beispiel","vocab.progress":"gelernt",
  "tests.title":"Tests & Quiz","tests.back":"Zurück","tests.search":"Suchen...","tests.pass":"Bestehen","tests.questions":"Fragen","tests.passed":"Bestanden!","tests.keep_practicing":"Weiter üben!","tests.score":"Punktzahl","tests.xp_earned":"EP","tests.submit":"Abgeben","tests.previous":"Zurück","tests.next":"Weiter",
  "exercise.title":"Übungsmodus","exercise.subtitle":"Thema wählen.","exercise.all_topics":"Alle","exercise.correct":"Richtig!","exercise.wrong":"Falsch. Antwort:","exercise.no_penalty":"Keine Strafe!","exercise.next_question":"Nächste","exercise.see_results":"Ergebnisse","exercise.new_session":"Neue Session","exercise.complete":"Fertig!","exercise.accuracy":"Genauigkeit","exercise.earned":"EP verdient",
  "mistakes.title":"Fehler Review","mistakes.subtitle":"Lerne aus Fehlern","mistakes.search":"Suchen...","mistakes.no_mistakes":"Keine Fehler!","mistakes.no_mistakes_msg":"Fehler erscheinen hier.","mistakes.no_match":"Keine","mistakes.total":"Gesamt","mistakes.unreviewed":"Ungesehen","mistakes.reviewed":"Gesehen","mistakes.review":"Als gesehen","mistakes.delete":"Löschen","mistakes.clear_all":"Alle löschen","mistakes.question":"Frage","mistakes.your_answer":"Deine Antwort","mistakes.correct_answer":"Richtige Antwort","mistakes.practice_again":"Nochmal","mistakes.source_exercise":"Übung","mistakes.source_test":"Test",
  "ai.title":"KI Tutor","ai.premium_ul":"Premium — unbegrenzt","ai.paywall":"Zahlung nötig","ai.unlock_btn":"Für 3€ freischalten","ai.unlock_title":"KI Tutor freischalten","ai.unlock_desc":"Unbegrenzte KI Grammatik, Übersetzung, Konversation.","ai.grammar_feat":"Grammatik Hilfe","ai.translate_feat":"Alles übersetzen","ai.convo_feat":"Konversation üben","ai.claude_feat":"Von Claude AI","ai.grammar_mode":"Grammatik","ai.translate_mode":"Übersetzung","ai.convo_mode":"Konversation","ai.grammar_desc":"Grammatik fragen","ai.translate_desc":"Sätze übersetzen","ai.convo_desc":"Natürlich sprechen","ai.powered_by":"von Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Sicheres PayPal",
  "profile.member_since":"Mitglied seit","profile.learning_langs":"Sprachen","profile.currently_learning":"Aktiv","profile.earned":"Verdient!","profile.membership":"Mitgliedschaft","profile.premium_member":"Premium","profile.free_plan":"Kostenlos","profile.manage":"Verwalten","profile.upgrade":"Upgrade","profile.this_week":"Diese Woche","profile.days_active":"von 7 Tagen",
  "settings.title":"Einstellungen","settings.account":"Konto","settings.preferences":"Präferenzen","settings.learning":"Lernen","settings.ai_tab":"KI","settings.change_email":"E-Mail ändern","settings.change_password":"Passwort ändern","settings.delete_account":"Konto löschen","settings.theme":"Design","settings.light":"Hell","settings.dark":"Dunkel","settings.ui_language":"Oberfläche","settings.learning_lang":"Lernsprache","settings.reset_progress":"Fortschritt löschen","settings.daily_goal":"Tagesziel",
  "nav.home":"Start","nav.grammar":"Grammatik","nav.words":"Wörter","nav.tests":"Tests","nav.practice":"Üben","nav.mistakes":"Fehler","nav.ai_chat":"KI Chat",
  "generic.back_dashboard":"Zurück","generic.cancel":"Abbrechen","generic.save":"Speichern","generic.loading":"Lädt...",
  "placeholder.email":"du@beispiel.de","placeholder.username":"name","placeholder.password":"Min. 6","placeholder.confirmPassword":"Bestätigen","placeholder.identifier":"name oder email","placeholder.passwordLogin":"Passwort",
};
const es: Dict = {
  "topbar.level":"Nivel","topbar.xp":"PX","topbar.logout":"Salir","topbar.streak":"días","topbar.uiLanguage":"Idioma",
  "login.title":"Bienvenido","login.subtitle":"Inicia sesión","login.identifier":"Usuario o email","login.password":"Contraseña","login.forgotPassword":"¿Olvidaste?","login.rememberMe":"Recordarme","login.submit":"Entrar","login.noAccount":"¿Sin cuenta?","login.createAccount":"Crear una","login.errorEmpty":"Completa todos.","login.errorInvalid":"Inválido.","login.errorGeneral":"Error.","login.forgotMsg":"Crea nueva cuenta si olvidaste.",
  "register.title":"Crear cuenta","register.subtitle":"Empieza hoy","register.email":"Email","register.username":"Usuario","register.password":"Contraseña","register.confirmPassword":"Confirmar","register.submit":"Registrar","register.hasAccount":"¿Ya tienes?","register.loginLink":"Entrar","register.errorEmailRequired":"Email necesario.","register.errorEmailFormat":"Email válido.","register.errorUsernameRequired":"Usuario necesario.","register.errorUsernameShort":"Mín. 3 caracteres.","register.errorUsernameChars":"Letras, números, guiones.","register.errorPasswordRequired":"Contraseña necesaria.","register.errorPasswordShort":"Mín. 6 caracteres.","register.errorConfirmRequired":"Confirma.","register.errorConfirmMatch":"No coinciden.","register.errorEmailExists":"Email ya existe.","register.errorUsernameTaken":"Usuario ya tomado.",
  "dashboard.welcome":"¡Bienvenido,","dashboard.noLanguagePrompt":"¡Elige un idioma!","dashboard.learningLanguage":"Aprendiendo","dashboard.level":"Nivel","dashboard.totalXP":"PX Total","dashboard.streak":"Racha","dashboard.days":"días","dashboard.language":"Idioma","dashboard.none":"Ninguno","dashboard.xpProgress":"Progreso","dashboard.needMoreXP":"Necesitas","dashboard.moreXP":"PX más","dashboard.dailyGoal":"Objetivo","dashboard.dailyGoalReached":"¡Objetivo!","dashboard.dailyGoalEmpty":"¡Haz ejercicio!","dashboard.continueLearning":"Continuar","dashboard.chooseLanguage":"Elige idioma","dashboard.streakActive":"días! ¡Sigue!","dashboard.streakAtRisk":"¡No pierdas!","dashboard.emptyStreak":"¡Empieza hoy!",
  "lang.en":"Inglés","lang.nl":"Neerlandés","lang.fr":"Francés","lang.de":"Alemán","lang.es":"Español",
  "wotd.title":"Palabra del Día","wotd.i_know":"La sé","wotd.show_hint":"¿Pista?","wotd.dont_know":"No la sé","wotd.learned":"¡Aprendida!","wotd.back_tomorrow":"Vuelve mañana","wotd.all_done":"¡Terminado!","wotd.all_done_msg":"Ya has practicado hoy.","wotd.review":"Repasar","wotd.words_learned":"palabras aprendidas","wotd.youre_done":"Terminado","wotd.see_tomorrow":"¡Hasta mañana!",
  "grammar.title":"Gramática","grammar.back_lessons":"Volver","grammar.learn":"Aprender","grammar.test":"Prueba","grammar.test_coming":"Prueba pronto","grammar.mark_complete":"Completar","grammar.completed":"Completado","grammar.search":"Buscar...","grammar.no_match":"Sin resultados.","grammar.exercises_title":"Ejercicios",
  "grammar.overview":"Lo que aprenderás","grammar.build":"Lo que puedes construir","grammar.conjugation":"Conjugación","grammar.rules":"Reglas de gramática","grammar.time_expr":"Expresiones de tiempo","grammar.details":"Explicación detallada","grammar.callouts":"Puntos importantes","grammar.mistakes_title":"Errores comunes","grammar.review":"Revisión rápida","grammar.qa":"Preguntas de práctica",
  "vocab.title":"Vocabulario","vocab.back":"Volver","vocab.mark_learned":"Marcar aprendida","vocab.learned":"Aprendida","vocab.search":"Buscar...","vocab.example":"Ejemplo","vocab.progress":"aprendidas",
  "tests.title":"Pruebas","tests.back":"Volver","tests.search":"Buscar...","tests.pass":"Aprobar","tests.questions":"preguntas","tests.passed":"¡Aprobado!","tests.keep_practicing":"¡Sigue!","tests.score":"Puntaje","tests.xp_earned":"PX","tests.submit":"Entregar","tests.previous":"Anterior","tests.next":"Siguiente",
  "exercise.title":"Práctica","exercise.subtitle":"Elige un tema.","exercise.all_topics":"Todos","exercise.correct":"¡Correcto!","exercise.wrong":"Mal. Respuesta:","exercise.no_penalty":"¡Sin penalización!","exercise.next_question":"Siguiente","exercise.see_results":"Resultados","exercise.new_session":"Nueva Sesión","exercise.complete":"¡Completo!","exercise.accuracy":"precisión","exercise.earned":"PX ganados",
  "mistakes.title":"Revisar Errores","mistakes.subtitle":"Aprende de tus errores","mistakes.search":"Buscar...","mistakes.no_mistakes":"¡Sin errores!","mistakes.no_mistakes_msg":"Errores aparecerán aquí.","mistakes.no_match":"Nada","mistakes.total":"Total","mistakes.unreviewed":"No vistos","mistakes.reviewed":"Vistos","mistakes.review":"Marcar visto","mistakes.delete":"Borrar","mistakes.clear_all":"Borrar todo","mistakes.question":"Pregunta","mistakes.your_answer":"Tu Respuesta","mistakes.correct_answer":"Correcta","mistakes.practice_again":"Otra vez","mistakes.source_exercise":"Ejercicio","mistakes.source_test":"Prueba",
  "ai.title":"Tutor IA","ai.premium_ul":"Premium — ilimitado","ai.paywall":"Pago necesario","ai.unlock_btn":"Desbloquear por 3€","ai.unlock_title":"Desbloquear Tutor IA","ai.unlock_desc":"Gramática, traducción y conversación ilimitadas.","ai.grammar_feat":"Gramática","ai.translate_feat":"Traducción","ai.convo_feat":"Conversación","ai.claude_feat":"Por Claude AI","ai.grammar_mode":"Gramática","ai.translate_mode":"Traducción","ai.convo_mode":"Conversación","ai.grammar_desc":"Reglas gramaticales","ai.translate_desc":"Traducir frases","ai.convo_desc":"Hablar naturalmente","ai.powered_by":"por Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"PayPal seguro",
  "profile.member_since":"Miembro desde","profile.learning_langs":"Idiomas","profile.currently_learning":"Activo","profile.earned":"¡Ganado!","profile.membership":"Membresía","profile.premium_member":"Premium","profile.free_plan":"Gratis","profile.manage":"Gestionar","profile.upgrade":"Mejorar","profile.this_week":"Esta Semana","profile.days_active":"de 7 días",
  "settings.title":"Ajustes","settings.account":"Cuenta","settings.preferences":"Preferencias","settings.learning":"Aprendizaje","settings.ai_tab":"IA","settings.change_email":"Cambiar Email","settings.change_password":"Cambiar Contraseña","settings.delete_account":"Borrar Cuenta","settings.theme":"Tema","settings.light":"Claro","settings.dark":"Oscuro","settings.ui_language":"Idioma","settings.learning_lang":"Idioma de Aprendizaje","settings.reset_progress":"Reiniciar","settings.daily_goal":"Objetivo XP",
  "nav.home":"Inicio","nav.grammar":"Gramática","nav.words":"Palabras","nav.tests":"Pruebas","nav.practice":"Práctica","nav.mistakes":"Errores","nav.ai_chat":"Chat IA",
  "generic.back_dashboard":"Volver","generic.cancel":"Cancelar","generic.save":"Guardar","generic.loading":"Cargando...",
  "placeholder.email":"tu@ejemplo.es","placeholder.username":"usuario","placeholder.password":"Mín. 6","placeholder.confirmPassword":"Confirmar","placeholder.identifier":"usuario o email","placeholder.passwordLogin":"Contraseña",
};

const all: Record<string, Dict> = { en, nl, fr, de, es };
export type TranslationKey = keyof typeof en;

export function getTranslation(lang: UILanguage, key: TranslationKey): string {
  const dict = all[lang] ?? en;
  return dict[key as string] ?? en[key as string] ?? key;
}
export function getTranslations(lang: UILanguage): Dict {
  return all[lang] ?? en;
}
