export type UILanguage = "en" | "nl" | "fr" | "de" | "es";
export const UI_LANGUAGES: { code: UILanguage; name: string; flag: string }[] = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Español", flag: "🇪🇸" },
];

type Dict = Record<string, string>;
const en: Dict = {
  // TopBar
  "topbar.level":"Level","topbar.xp":"XP","topbar.logout":"Log out","topbar.streak":"day streak","topbar.uiLanguage":"Interface language",
  // Login
  "login.title":"Welcome back","login.subtitle":"Log in to continue","login.identifier":"Username or Email","login.password":"Password","login.forgotPassword":"Forgot password?","login.rememberMe":"Remember me","login.submit":"Log in","login.noAccount":"Don't have an account?","login.createAccount":"Create one","login.errorEmpty":"Please fill in all fields.","login.errorInvalid":"Invalid credentials.","login.errorGeneral":"Something went wrong.","login.forgotMsg":"Please create a new account if you forgot your password.",
  // Register
  "register.title":"Create your account","register.subtitle":"Start learning today","register.email":"Email","register.username":"Username","register.password":"Password","register.confirmPassword":"Confirm Password","register.submit":"Register","register.hasAccount":"Already have an account?","register.loginLink":"Log in","register.errorEmailRequired":"Email is required.","register.errorEmailFormat":"Please enter a valid email.","register.errorUsernameRequired":"Username is required.","register.errorUsernameShort":"Username must be at least 3 characters.","register.errorUsernameChars":"Only letters, numbers and underscores.","register.errorPasswordRequired":"Password is required.","register.errorPasswordShort":"Password must be at least 6 characters.","register.errorConfirmRequired":"Please confirm your password.","register.errorConfirmMatch":"Passwords do not match.","register.errorEmailExists":"An account with this email already exists.","register.errorUsernameTaken":"This username is already taken.",
  // Dashboard
  "dashboard.welcome":"Welcome back,","dashboard.noLanguagePrompt":"Pick a language below to start learning!","dashboard.learningLanguage":"Learning","dashboard.level":"Level","dashboard.totalXP":"Total XP","dashboard.streak":"Streak","dashboard.days":"days","dashboard.language":"Language","dashboard.none":"None","dashboard.xpProgress":"Progress to Level","dashboard.needMoreXP":"You need","dashboard.moreXP":"more XP to reach Level","dashboard.dailyGoal":"Today's Goal","dashboard.dailyGoalReached":"Goal reached! Great job!","dashboard.dailyGoalEmpty":"Do a quick exercise to get started!","dashboard.continueLearning":"Continue Learning","dashboard.chooseLanguage":"Choose your language","dashboard.streakActive":"day streak! Keep going!","dashboard.streakAtRisk":"Don't lose your streak!","dashboard.emptyStreak":"Start your streak today!",
  "dashboard.legend":"Legend","dashboard.legendSub":"Season levels. Unlock, play, earn XP.","dashboard.grammarBtn":"Grammar Lessons","dashboard.grammarBtnSub":"Step-by-step grammar guides with exercises.","dashboard.mistakeBtn":"Mistake Review","dashboard.mistakeBtnSub":"Learn from your mistakes & improve.","dashboard.testBtn":"Tests & Quizzes","dashboard.testSub":"Challenge yourself.","dashboard.arenaBtnSub":"Season levels. Unlock, play, earn XP.","dashboard.wotdBtn":"Word of the Day","dashboard.wotdBtnSub":"Learn a new word daily. Expand your vocabulary!","dashboard.7dayChampion":"🏆 7-day champion","dashboard.streak7dayBadge":"⭐ 7-day streak","dashboard.continueIn":"Pick up exactly where you left off","dashboard.continueInLang":"Pick up where you left off in","dashboard.milestone30":"30-day champion","dashboard.milestone7":"7-day streak",
  // Language names
  "lang.en":"English","lang.nl":"Dutch","lang.fr":"French","lang.de":"German","lang.es":"Spanish",
  // WOTD
  "wotd.title":"Word of the Day","wotd.i_know":"I Know This","wotd.show_hint":"Need a hint?","wotd.dont_know":"I Don't Know","wotd.learned":"Learned!","wotd.back_tomorrow":"Come back tomorrow for your next word","wotd.all_done":"All Done for Today!","wotd.all_done_msg":"You've already practiced today.","wotd.review":"Review Words","wotd.words_learned":"words learned","wotd.youre_done":"You're Done for Today","wotd.see_tomorrow":"See you tomorrow!",
  // Grammar
  "grammar.title":"Grammar Lessons","grammar.back_lessons":"Back to Lessons","grammar.learn":"Learn","grammar.test":"Test","grammar.test_coming":"Test coming soon","grammar.mark_complete":"Mark as Complete","grammar.completed":"Completed","grammar.search":"Search lessons...","grammar.no_match":"No lessons match.","grammar.exercises_title":"Quick Exercises",
  "grammar.overview":"What you'll learn","grammar.build":"What you can build","grammar.conjugation":"Conjugation","grammar.rules":"Grammar rules","grammar.time_expr":"Time expressions","grammar.details":"Detailed explanation","grammar.callouts":"Important points","grammar.mistakes_title":"Common mistakes","grammar.review":"Quick review","grammar.qa":"Practice questions",
  // Vocabulary
  "vocab.title":"Vocabulary","vocab.back":"Back to Vocabulary","vocab.mark_learned":"Mark as Learned","vocab.learned":"Learned","vocab.search":"Search words...","vocab.example":"Example","vocab.progress":"learned",
  // Tests
  "tests.title":"Tests & Quizzes","tests.back":"Back to Tests","tests.search":"Search tests...","tests.pass":"Pass","tests.questions":"questions","tests.passed":"Test Passed!","tests.keep_practicing":"Keep Practicing!","tests.score":"Score","tests.xp_earned":"XP Earned","tests.submit":"Submit Test","tests.previous":"Previous","tests.next":"Next",
  // Exercise
  "exercise.title":"Practice Mode","exercise.subtitle":"Pick a topic and answer questions.","exercise.all_topics":"All Topics","exercise.correct":"Correct!","exercise.wrong":"Not quite. Correct answer:","exercise.no_penalty":"No XP penalty — keep going!","exercise.next_question":"Next Question","exercise.see_results":"See Results","exercise.new_session":"New Session","exercise.complete":"Practice Complete!","exercise.accuracy":"accuracy","exercise.earned":"XP earned",
  // Mistakes
  "mistakes.title":"Mistake Review","mistakes.subtitle":"Learn from your mistakes","mistakes.search":"Search mistakes...","mistakes.no_mistakes":"No mistakes yet!","mistakes.no_mistakes_msg":"Mistakes will appear here.","mistakes.no_match":"No matches","mistakes.total":"Total","mistakes.unreviewed":"Unreviewed","mistakes.reviewed":"Reviewed","mistakes.review":"Mark as Reviewed","mistakes.delete":"Delete","mistakes.clear_all":"Clear all","mistakes.question":"Question","mistakes.your_answer":"Your Answer","mistakes.correct_answer":"Correct Answer","mistakes.practice_again":"Practice Again","mistakes.source_exercise":"Practice","mistakes.source_test":"Test",
  // AI
  "ai.title":"AI Tutor","ai.premium_ul":"Premium — unlimited","ai.paywall":"Payment required","ai.unlock_btn":"EUR 4.00 / 30 days via Ko-fi","ai.unlock_title":"Unlock AI Tutor","ai.unlock_desc":"Get AI grammar, translations, and conversation for 30 days.","ai.grammar_feat":"Grammar explanations","ai.translate_feat":"Translate anything","ai.convo_feat":"Conversation practice","ai.claude_feat":"Powered by Claude AI","ai.grammar_mode":"Grammar Help","ai.translate_mode":"Translation","ai.convo_mode":"Conversation","ai.grammar_desc":"Ask about any grammar rule","ai.translate_desc":"Translate phrases & sentences","ai.convo_desc":"Practice speaking naturally","ai.powered_by":"powered by Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Secure Ko-fi",
  // Profile
  "profile.member_since":"Member since","profile.learning_langs":"Learning Languages","profile.earned":"Earned!","profile.membership":"Membership","profile.premium_member":"Premium Member","profile.free_plan":"Free Plan","profile.manage":"Manage","profile.upgrade":"Upgrade","profile.currently_learning":"Currently learning","profile.active":"Active","profile.premiumStatus":"{role} — Unlimited AI, no ads","profile.freeStatus":"5 AI messages/day, ads & basic features","profile.quickLinks":"Quick Links","profile.settings":"Settings","profile.totalXP":"Total XP","profile.levelStat":"Level","profile.currentStreak":"Current Streak","profile.longestStreak":"Longest Streak","profile.levelProgress":"Level Progress","profile.xpToNext":"{xpCurrent} / {xpNeeded} XP → Level {nextLevel}","profile.thisWeek":"This Week","profile.daysActiveThisWeek":"{activeDays} of 7 days active this week","profile.achievements":"Achievements","profile.sevenDayStreak":"🔥 7-Day Streak","profile.thirtyDayStreak":"🏆 30-Day Streak","profile.firstLesson":"⭐ First Lesson","profile.goalCrusher":"🎯 Goal Crusher","profile.scholar":"📚 Scholar","profile.xpWarrior":"💪 XP Warrior","profile.backToDashboard":"Back to Dashboard",
  // Settings
  "settings.title":"Settings","settings.back":"Back to Dashboard","settings.account":"Account","settings.preferences":"Preferences","settings.learning":"Learning","settings.ai_tab":"AI","settings.changeEmail":"Change Email","settings.changePassword":"Change Password","settings.deleteAccount":"Delete Account","settings.theme":"Theme","settings.light":"Light","settings.dark":"Dark","settings.uiLanguage":"Interface Language","settings.learningLang":"Learning Language","settings.resetProgress":"Reset Progress","settings.dailyGoal":"Daily XP Goal","settings.currentMembership":"Current Membership","settings.premium":"Premium","settings.free":"Free","settings.manage":"Manage","settings.upgrade":"Upgrade","settings.thisWeek":"This Week","settings.daysActive":"of 7 days active","settings.earned":"Earned!","settings.never":"Never","settings.demoMode":"(Demo) configuration stored in localStorage — go to Vercel for real deployment.","settings.aiModel":"AI Model","settings.paypalClientID":"Ko-fi Client ID","settings.paypalPublic":"(public)","settings.onlySetting":"This is the ONLY setting you need. Put your Ko-fi Client ID here.","settings.saveConfig":"Save Configuration","settings.saved":"✅ Saved!","settings.savedNote":"✅ No API keys in browser or GitHub.","settings.deployNote":"Deploy to Vercel, set environment variables in dashboard.","settings.currentEmail":"Current email","settings.newEmail":"New email","settings.emailConfirm":"Current password (to confirm)","settings.updateEmail":"Update Email","settings.loginPrompt":"(Demo — only logged-in users appear for this email.)","settings.resetWarning":"This resets your XP, level, and streak to zero. Your account and settings remain.","settings.resetConfirm":"Reset all learning progress? This cannot be undone.","settings.resetAllProgress":"Reset All Progress","settings.defaultGoal":"Default: 50 XP. Custom goals will be available in a future update.","settings.memberSince":"Member since","settings.accountInfo":"You can change your email or password here.",
  // Nav
  "nav.home":"Home","nav.profile":"Profile","nav.grammar":"Grammar","nav.words":"Words","nav.tests":"Tests","nav.wotd":"WOTD","nav.practice":"Practice","nav.mistakes":"Mistakes","nav.ai_chat":"AI Chat","nav.arena":"Legend",
  // Arena
  "arena.back":"← Dashboard","arena.subtitle":"Complete seasons. Earn XP. Become fluent.","arena.noContent":"No content for {lang}","arena.noContentNote":"Add seasons to public/arena-questions.json","arena.active":"Active","arena.done":"Done","arena.locked":"Locked","arena.levelComplete":"Completed","arena.levelLocked":"","arena.levelQuestions":"{count} questions","arena.tryAgain":"Try again","arena.backToSeasons":"← All Seasons",
  // TestPage
  "testpage.back":"← Dashboard","testpage.testsTitle":"📝 {flag} Tests","testpage.allLevels":"All Levels","testpage.levelFocus":"Showing all levels - tap a level to focus","testpage.noTests":"No tests found","testpage.questions":"questions","testpage.passRequirement":"Pass:{score}%","testpage.xpBonus":"+Bonus XP","testpage.matchPassed":"Test Passed!","testpage.matchPracticing":"Keep Practicing!","testpage.score":"Score","testpage.xpEarned":"XP Earned","testpage.backToTests":"← Back to Tests","testpage.dashboard":"Dashboard",
// GrammarPage
   "grammarpage.back":"← Dashboard","grammarpage.searchPlaceholder":"Search lessons...","grammarpage.allLevels":"All Levels","testpage.lessons":"lessons","testpage.results":"results","testpage.clear":"clear","testpage.noLessons":"No lessons found",
  // VocabPage
  "vocabpage.back":"Back to Dashboard","vocabpage.learnedCount":"{learned}/{total} learned",
  // MistakesPage
  "mistakespage.back":"← Mistakes","mistakespage.backDetail":"Back to Mistakes","mistakespage.practiceAgain":"Practice Again","mistakespage.sourcePractice":"Practice","mistakespage.sourceTest":"Test","mistakesreview.noMistakes":"🎉 No mistakes yet!","mistakessearch.noMistakesMsg":"Keep practicing.","mistakeslevel.noResults":"Clear all mistakes","mistakesdate.clearAll":"Clear all mistakes","mistakesquestion.answered":"✅ answered!","mistakesview.unreviewed":"Unreviewed","mistakesview.reviewed":"Reviewed","mistakesview.all":"all",
  // Misc
  "placeholder.email":"you@example.com","placeholder.username":"username","placeholder.password":"Min. 6 characters","placeholder.confirmPassword":"Re-enter password","placeholder.identifier":"username or email","placeholder.passwordLogin":"Enter password",
};
const nl: Dict = {
  "topbar.level":"Niveau","topbar.xp":"EP","topbar.logout":"Uitloggen","topbar.streak":"dagen streak","topbar.uiLanguage":"Interface taal",
  "login.title":"Welkom terug","login.subtitle":"Log in om verder te leren","login.identifier":"Gebruikersnaam of e-mail","login.password":"Wachtwoord","login.forgotPassword":"Wachtwoord vergeten?","login.rememberMe":"Onthoud mij","login.submit":"Inloggen","login.noAccount":"Nog geen account?","login.createAccount":"Account aanmaken","login.errorEmpty":"Vul alle velden in.","login.errorInvalid":"Ongeldige inloggegevens.","login.errorGeneral":"Er is iets misgegaan.","login.forgotMsg":"Maak een nieuw account aan als u uw wachtwoord bent vergeten.",
  "register.title":"Account aanmaken","register.subtitle":"Begin vandaag met leren","register.email":"E-mail","register.username":"Gebruikersnaam","register.password":"Wachtwoord","register.confirmPassword":"Bevestig wachtwoord","register.submit":"Registreren","register.hasAccount":"Heb je al een account?","register.loginLink":"Inloggen","register.errorEmailRequired":"E-mail is verplicht.","register.errorEmailFormat":"Voer een geldig e-mailadres in.","register.errorUsernameRequired":"Gebruikersnaam is verplicht.","register.errorUsernameShort":"Minimaal 3 tekens.","register.errorUsernameChars":"Alleen letters, cijfers en underscores.","register.errorPasswordRequired":"Wachtwoord is verplicht.","register.errorPasswordShort":"Minimaal 6 tekens.","register.errorConfirmRequired":"Bevestig je wachtwoord.","register.errorConfirmMatch":"Wachtwoorden komen niet overeen.","register.errorEmailExists":"Dit e-mailadres bestaat al.","register.errorUsernameTaken":"Deze gebruikersnaam is al in gebruik.",
  "dashboard.welcome":"Welkom terug,","dashboard.noLanguagePrompt":"Kies een taal om te beginnen!","dashboard.learningLanguage":"Leren","dashboard.level":"Niveau","dashboard.totalXP":"Totale EP","dashboard.streak":"Streak","dashboard.days":"dagen","dashboard.language":"Taal","dashboard.none":"Geen","dashboard.xpProgress":"Voortgang naar Niveau","dashboard.needMoreXP":"Je hebt nog","dashboard.moreXP":"EP nodig voor Niveau","dashboard.dailyGoal":"Doel van Vandaag","dashboard.dailyGoalReached":"Doel behaald! Goed gedaan!","dashboard.dailyGoalEmpty":"Doe een snelle oefening!","dashboard.continueLearning":"Verder Leren","dashboard.chooseLanguage":"Kies je taal","dashboard.streakActive":"dagen streak! Ga door!","dashboard.streakAtRisk":"Verlies je streak niet!","dashboard.emptyStreak":"Begin je streak vandaag!",
  "dashboard.legend":"Legende","dashboard.legendSub":"Seizoen levels. Ontgrendel, speel, verdien EP.","dashboard.grammarBtn":"Grammatica Lessen","dashboard.grammarBtnSub":"Stap-voor-stap grammaticagids met oefeningen.","dashboard.mistakeBtn":"Fouten Review","dashboard.mistakeBtnSub":"Leer van je fouten & verbeter.","dashboard.testBtn":"Toetsen & Quizzen","dashboard.testSub":"Doe je best.","dashboard.arenaBtnSub":"Seizoen levels. Ontgrendel, speel, verdien EP.","dashboard.wotdBtn":"Woord van de Dag","dashboard.wotdBtnSub":"Leer dagelijks een nieuw woord.","dashboard.7dayChampion":"🏆 7-daags kampioen","dashboard.streak7dayBadge":"⭐ 7-daags streak","dashboard.continueIn":"Ga verder waar je gebleven was","dashboard.continueInLang":"Ga verder in","dashboard.milestone30":"30-daags kampioen","dashboard.milestone7":"7-daags streak",
  "lang.en":"Engels","lang.nl":"Nederlands","lang.fr":"Frans","lang.de":"Duits","lang.es":"Spaans",
  "wotd.title":"Woord van de Dag","wotd.i_know":"Ik Ken Het","wotd.show_hint":"Hint nodig?","wotd.dont_know":"Ik Ken Het Niet","wotd.learned":"Geleerd!","wotd.back_tomorrow":"Kom morgen terug","wotd.all_done":"Klaar voor Vandaag!","wotd.all_done_msg":"Je hebt vandaag al geoefend.","wotd.review":"Herhaal Woorden","wotd.words_learned":"woorden geleerd","wotd.youre_done":"Klaar voor Vandaag","wotd.see_tomorrow":"Tot morgen!",
  "grammar.title":"Grammatica Lessen","grammar.back_lessons":"Terug naar Lessen","grammar.learn":"Leren","grammar.test":"Toets","grammar.test_coming":"Toets volgt","grammar.mark_complete":"Markeer als Voltooid","grammar.completed":"Voltooid","grammar.search":"Lessen zoeken...","grammar.no_match":"Geen lessen gevonden.","grammar.exercises_title":"Snelle Oefeningen",
  "grammar.overview":"Wat ga je leren","grammar.build":"Wat je kunt bouwen","grammar.conjugation":"Vervoeging","grammar.rules":"Grammaticaregels","grammar.time_expr":"Tijdsuitdrukkingen","grammar.details":"Gedetailleerde uitleg","grammar.callouts":"Belangrijke punten","grammar.mistakes_title":"Veelgemaakte fouten","grammar.review":"Snelle herhaling","grammar.qa":"Oefenvragen",
  "vocab.title":"Woordenschat","vocab.back":"Terug naar Woorden","vocab.mark_learned":"Markeer als Geleerd","vocab.learned":"Geleerd","vocab.search":"Woorden zoeken...","vocab.example":"Voorbeeld","vocab.progress":"geleerd",
  "tests.title":"Toetsen & Quizzen","tests.back":"Terug naar Toetsen","tests.search":"Toetsen zoeken...","tests.pass":"Slaag","tests.questions":"vragen","tests.passed":"Geslaagd!","tests.keep_practicing":"Blijf Oefenen!","tests.score":"Score","tests.xp_earned":"EP Verdiend","tests.submit":"Toets Inleveren","tests.previous":"Vorige","tests.next":"Volgende",
  "exercise.title":"Oefenmodus","exercise.subtitle":"Kies een onderwerp en beantwoord vragen.","exercise.all_topics":"Alle Onderwerpen","exercise.correct":"Correct!","exercise.wrong":"Niet goed. Correct antwoord:","exercise.no_penalty":"Geen EP straf — ga door!","exercise.next_question":"Volgende Vraag","exercise.see_results":"Zie Resultaten","exercise.new_session":"Nieuwe Sessie","exercise.complete":"Oefening Voltooid!","exercise.accuracy":"nauwkeurigheid","exercise.earned":"EP verdiend",
  "mistakes.title":"Fout Review","mistakes.subtitle":"Leer van je fouten","mistakes.search":"Fouten zoeken...","mistakes.no_mistakes":"Nog geen fouten!","mistakes.no_mistakes_msg":"Fouten verschijnen hier.","mistakes.no_match":"Geen resultaten","mistakes.total":"Totaal","mistakes.unreviewed":"Onbekeken","mistakes.reviewed":"Bekeken","mistakes.review":"Markeer als Bekeken","mistakes.delete":"Verwijder","mistakes.clear_all":"Alles wissen","mistakes.question":"Vraag","mistakes.your_answer":"Jouw Antwoord","mistakes.correct_answer":"Juiste Antwoord","mistakes.practice_again":"Opnieuw Oefenen","mistakes.source_exercise":"Oefening","mistakes.source_test":"Toets",
  "ai.title":"AI Tutor","ai.premium_ul":"Premium — onbeperkt","ai.paywall":"Betaling nodig","ai.unlock_btn":"EUR 4.00 / 30 days via Ko-fi","ai.unlock_title":"AI Tutor Ontgrendelen","ai.unlock_desc":"AI grammatica, vertalingen en conversatie voor 30 dagen.","ai.grammar_feat":"Grammatica uitleg","ai.translate_feat":"Alles vertalen","ai.convo_feat":"Conversatie oefenen","ai.claude_feat":"Aangedreven door Claude AI","ai.grammar_mode":"Grammatica Hulp","ai.translate_mode":"Vertaling","ai.convo_mode":"Conversatie","ai.grammar_desc":"Vraag over grammatica regels","ai.translate_desc":"Vertaal zinnen","ai.convo_desc":"Oefen natuurlijk spreken","ai.powered_by":"aangedreven door Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Veilige Ko-fi",
  "profile.member_since":"Lid sinds","profile.learning_langs":"Talen Leren","profile.earned":"Verdiend!","profile.membership":"Lidmaatschap","profile.premium_member":"Premium Lid","profile.free_plan":"Gratis Plan","profile.manage":"Beheer","profile.upgrade":"Upgrade","profile.currently_learning":"Nu aan het leren","profile.active":"Actief","profile.premiumStatus":"{role} — Onbeperkt AI, geen advertenties","profile.freeStatus":"5 AI-berichten/dag, advertenties & basis functies","profile.quickLinks":"Quick Links","profile.settings":"Instellingen","profile.totalXP":"Totale EP","profile.levelStat":"Niveau","profile.currentStreak":"Huidige Streak","profile.longestStreak":"Langste Streak","profile.levelProgress":"Niveau Voortgang","profile.xpToNext":"{xpCurrent} / {xpNeeded} EP → Niveau {nextLevel}","profile.thisWeek":"Deze Week","profile.daysActiveThisWeek":"{activeDays} van 7 dagen actief deze week","profile.achievements":"Prestaties","profile.sevenDayStreak":"🔥 7-daags Streak","profile.thirtyDayStreak":"🏆 30-daags Streak","profile.firstLesson":"⭐ Eerste Les","profile.goalCrusher":"🎯 Goal Crusher","profile.scholar":"📚 Geleerde","profile.xpWarrior":"💪 XP Strijder","profile.backToDashboard":"Terug naar Dashboard",
  "settings.title":"Instellingen","settings.back":"Terug naar Dashboard","settings.account":"Account","settings.preferences":"Voorkeuren","settings.learning":"Leren","settings.ai_tab":"AI","settings.changeEmail":"E-mail Wijzigen","settings.changePassword":"Wachtwoord Wijzigen","settings.deleteAccount":"Account Verwijderen","settings.theme":"Thema","settings.light":"Licht","settings.dark":"Donker","settings.uiLanguage":"Interface Taal","settings.learningLang":"Leer Taal","settings.resetProgress":"Voortgang Resetten","settings.dailyGoal":"Dagelijks XP Doel","settings.currentMembership":"Huidig Lidmaatschap","settings.premium":"Premium","settings.free":"Gratis","settings.manage":"Beheer","settings.upgrade":"Upgrade","settings.thisWeek":"Deze Week","settings.daysActive":"van 7 dagen actief","settings.earned":"Verdiend!","settings.never":"Nooit","settings.demoMode":"(Demo) configuratie opgeslagen in localStorage — ga naar Vercel voor echte implementatie.","settings.aiModel":"AI Model","settings.paypalClientID":"Ko-fi Client ID","settings.paypalPublic":"(publiek)","settings.onlySetting":"Dit is de ENIGE instelling die u nodig heeft.","settings.saveConfig":"Configuratie Opslaan","settings.saved":"✅ Opgeslagen!","settings.savedNote":"✅ Geen API-sleutels in browser of GitHub.","settings.deployNote":"Deploy naar Vercel, stel omgevingsvariabelen in.","settings.currentEmail":"Huidig e-mailadres","settings.newEmail":"Nieuw e-mailadres","settings.emailConfirm":"Huidig wachtwoord (ter bevestiging)","settings.updateEmail":"E-mail Bijwerken","settings.loginPrompt":"(Demo — alleen ingelogde gebruikers verschijnen voor dit e-mailadres.)","settings.resetWarning":"Dit zet je XP, niveau en streak op nul. Je account en instellingen blijven behouden.","settings.resetConfirm":"Alle leer voortgang resetten? Dit kan niet ongedaan gemaakt worden.","settings.resetAllProgress":"Alle Voortgang Resetten","settings.defaultGoal":"Standaard: 50 XP. Aangepaste doelen komen beschikbaar in een toekomstige update.","settings.memberSince":"Lid sinds","settings.accountInfo":"Je kunt hier je e-mailadres of wachtwoord wijzigen.",
  "nav.home":"Home","nav.profile":"Profiel","nav.grammar":"Grammatica","nav.words":"Woorden","nav.tests":"Toetsen","nav.practice":"Oefenen","nav.mistakes":"Fouten","nav.ai_chat":"AI Chat",
  "generic.back_dashboard":"Terug naar Dashboard","generic.cancel":"Annuleren","generic.save":"Opslaan","generic.loading":"Laden...",
  "placeholder.email":"jij@voorbeeld.nl","placeholder.username":"gebruikersnaam","placeholder.password":"Min. 6 tekens","placeholder.confirmPassword":"Voer wachtwoord opnieuw in","placeholder.identifier":"gebruikersnaam of email","placeholder.passwordLogin":"Voer wachtwoord in",
};
const fr: Dict = {
  "topbar.level":"Niveau","topbar.xp":"XP","topbar.logout":"D?connexion","topbar.streak":"jours","topbar.uiLanguage":"Langue interface",
  "login.title":"Bon retour","login.subtitle":"Connectez-vous","login.identifier":"Nom d'utilisateur ou email","login.password":"Mot de passe","login.forgotPassword":"Mot de passe oubli?","login.rememberMe":"Se souvenir","login.submit":"Connexion","login.noAccount":"Pas de compte?","login.createAccount":"Cr?er un compte","login.errorEmpty":"Remplissez tous les champs.","login.errorInvalid":"Identifiants invalides.","login.errorGeneral":"Une erreur est survenue.","login.forgotMsg":"Cr?ez un nouveau compte si vous avez oubli?.",
  "register.title":"Cr?er un compte","register.subtitle":"Commencez ? apprendre","register.email":"Email","register.username":"Nom d'utilisateur","register.password":"Mot de passe","register.confirmPassword":"Confirmer","register.submit":"S'inscrire","register.hasAccount":"D?j? un compte?","register.loginLink":"Connexion","register.errorEmailRequired":"Email requis.","register.errorEmailFormat":"Email invalide.","register.errorUsernameRequired":"Nom requis.","register.errorUsernameShort":"Min. 3 caract?res.","register.errorUsernameChars":"Lettres, chiffres, underscores.","register.errorPasswordRequired":"Mot de passe requis.","register.errorPasswordShort":"Min. 6 caract?res.","register.errorConfirmRequired":"Confirmez.","register.errorConfirmMatch":"Ne correspondent pas.","register.errorEmailExists":"Email d?j? utilis?.","register.errorUsernameTaken":"Nom d?j? pris.",
  "dashboard.welcome":"Bon retour,","dashboard.noLanguagePrompt":"Choisissez une langue!","dashboard.learningLanguage":"Apprentissage","dashboard.level":"Niveau","dashboard.totalXP":"XP Total","dashboard.streak":"S?rie","dashboard.days":"jours","dashboard.language":"Langue","dashboard.none":"Aucune","dashboard.xpProgress":"Progression","dashboard.needMoreXP":"Besoin de","dashboard.moreXP":"XP de plus","dashboard.dailyGoal":"Objectif du Jour","dashboard.dailyGoalReached":"Objectif atteint!","dashboard.dailyGoalEmpty":"Faites un exercice!","dashboard.continueLearning":"Continuer","dashboard.chooseLanguage":"Choisir langue","dashboard.streakActive":"jours! Continuez!","dashboard.streakAtRisk":"Ne perdez pas!","dashboard.emptyStreak":"Commencez aujourd'hui!",
  "dashboard.legend":"L?gende","dashboard.legendSub":"Niveaux de saison. D?bloquez, jouez, gagnez de l'XP.","dashboard.grammarBtn":"LeÃ§ons de Grammaire","dashboard.grammarBtnSub":"Guides de grammaire ?tape par ?tape avec exercices.","dashboard.mistakeBtn":"Revue d'Erreurs","dashboard.mistakeBtnSub":"Apprenez de vos erreurs & progressez.","dashboard.testBtn":"Tests & Quiz","dashboard.testSub":"Mettez-vous au d?fi!","dashboard.arenaBtnSub":"Niveaux de saison. D?bloquez, jouez, gagnez de l'XP.","dashboard.wotdBtn":"Mot du Jour","dashboard.wotdBtnSub":"Apprenez un nouveau mot chaque jour.","dashboard.7dayChampion":"🏆 Champion de 7 jours","dashboard.streak7dayBadge":"⭐ S?rie de 7 jours","dashboard.continueIn":"Continuez exactement oÃ¹ vous ?tiez","dashboard.continueInLang":"Continuez en","dashboard.milestone30":"Champion de 30 jours","dashboard.milestone7":"S?rie de 7 jours",
  "lang.en":"Anglais","lang.nl":"N?erlandais","lang.fr":"Français","lang.de":"Allemand","lang.es":"Espagnol",
  "wotd.title":"Mot du Jour","wotd.i_know":"Je le sais","wotd.show_hint":"Un indice?","wotd.dont_know":"Je ne sais pas","wotd.learned":"Appris!","wotd.back_tomorrow":"Revenez demain","wotd.all_done":"Termin?!","wotd.all_done_msg":"Vous avez d?j? pratiqu?.","wotd.review":"R?viser","wotd.words_learned":"mots appris","wotd.youre_done":"Termin?","wotd.see_tomorrow":"Ã€ demain!",
  "grammar.title":"LeÃ§ons de Grammaire","grammar.back_lessons":"Retour","grammar.learn":"Apprendre","grammar.test":"Test","grammar.test_coming":"Test bientÃ´t","grammar.mark_complete":"Marquer fini","grammar.completed":"Termin?","grammar.search":"Rechercher...","grammar.no_match":"Aucun r?sultat.","grammar.exercises_title":"Exercices Rapides",
  "grammar.overview":"Ce que tu vas apprendre","grammar.build":"Ce que tu peux construire","grammar.conjugation":"Conjugaison","grammar.rules":"R?gles de grammaire","grammar.time_expr":"Expressions de temps","grammar.details":"Explication d?taill?e","grammar.callouts":"Points importants","grammar.mistakes_title":"Erreurs courantes","grammar.review":"R?vision rapide","grammar.qa":"Questions pratiques",
  "vocab.title":"Vocabulaire","vocab.back":"Retour","vocab.mark_learned":"Marquer appris","vocab.learned":"Appris","vocab.search":"Rechercher...","vocab.example":"Exemple","vocab.progress":"appris",
  "tests.title":"Tests & Quiz","tests.back":"Retour","tests.search":"Rechercher...","tests.pass":"R?ussite","tests.questions":"questions","tests.passed":"R?ussi!","tests.keep_practicing":"Continuez!","tests.score":"Score","tests.xp_earned":"XP Gagn?","tests.submit":"Soumettre","tests.previous":"Pr?c?dent","tests.next":"Suivant",
  "exercise.title":"Mode Pratique","exercise.subtitle":"Choisissez un sujet.","exercise.all_topics":"Tous","exercise.correct":"Correct!","exercise.wrong":"Incorrect. R?ponse:","exercise.no_penalty":"Pas de p?nalit?!","exercise.next_question":"Suivante","exercise.see_results":"R?sultats","exercise.new_session":"Nouvelle Session","exercise.complete":"Termin?!","exercise.accuracy":"pr?cision","exercise.earned":"XP gagn?",
  "mistakes.title":"Revue d'Erreurs","mistakes.subtitle":"Apprenez de vos erreurs","mistakes.search":"Rechercher...","mistakes.no_mistakes":"Pas d'erreurs!","mistakes.no_mistakes_msg":"Les erreurs apparaÃ®tront ici.","mistakes.no_match":"Aucun","mistakes.total":"Total","mistakes.unreviewed":"Non vus","mistakes.reviewed":"Vus","mistakes.review":"Marquer vu","mistakes.delete":"Supprimer","mistakes.clear_all":"Tout effacer","mistakes.question":"Question","mistakes.your_answer":"Votre R?ponse","mistakes.correct_answer":"Bonne R?ponse","mistakes.practice_again":"Refaire","mistakes.source_exercise":"Exercice","mistakes.source_test":"Test",
  "ai.title":"Tuteur IA","ai.premium_ul":"Premium — illimit?","ai.paywall":"Paiement requis","ai.unlock_btn":"EUR 4.00 / 30 days via Ko-fi","ai.unlock_title":"D?bloquer Tuteur IA","ai.unlock_desc":"Grammaire, traductions, conversation illimit?es.","ai.grammar_feat":"Explications grammaire","ai.translate_feat":"Tout traduire","ai.convo_feat":"Conversation","ai.claude_feat":"Par Claude AI","ai.grammar_mode":"Aide Grammaire","ai.translate_mode":"Traduction","ai.convo_mode":"Conversation","ai.grammar_desc":"R?gles de grammaire","ai.translate_desc":"Traduire des phrases","ai.convo_desc":"Parler naturellement","ai.powered_by":"par Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Ko-fi s?curis?",
  "profile.member_since":"Membre depuis","profile.learning_langs":"Langues","profile.earned":"Gagn?!","profile.membership":"Abonnement","profile.premium_member":"Membre Premium","profile.free_plan":"Gratuit","profile.manage":"G?rer","profile.upgrade":"Am?liorer","profile.currently_learning":"En cours","profile.active":"Actif","profile.premiumStatus":"{role} — IA illimit?e, sans pub","profile.freeStatus":"5 messages IA/jour, pubs & fonctionnalit?s de base","profile.quickLinks":"Liens Rapides","profile.settings":"Param?tres","profile.totalXP":"XP Total","profile.levelStat":"Niveau","profile.currentStreak":"S?rie Actuelle","profile.longestStreak":"S?rie la Plus Longue","profile.levelProgress":"Progression de Niveau","profile.xpToNext":"{xpCurrent} / {xpNeeded} XP vers Niveau {nextLevel}","profile.thisWeek":"Cette Semaine","profile.daysActiveThisWeek":"{activeDays} sur 7 jours actifs","profile.achievements":"Accomplissements","profile.sevenDayStreak":"🔥 S?rie de 7 Jours","profile.thirtyDayStreak":"🏆 S?rie de 30 Jours","profile.firstLesson":"⭐ Premi?re LeÃ§on","profile.goalCrusher":"🎯 Goal Crusher","profile.scholar":"📚 Ã‰tudiant","profile.xpWarrior":"💪 Guerrier d'XP","profile.backToDashboard":"Retour",
  "settings.title":"Param?tres","settings.back":"Retour","settings.account":"Compte","settings.preferences":"Pr?f?rences","settings.learning":"Apprentissage","settings.ai_tab":"IA","settings.changeEmail":"Changer l'Email","settings.changePassword":"Changer le Mot de passe","settings.deleteAccount":"Supprimer le Compte","settings.theme":"Th?me","settings.light":"Clair","settings.dark":"Sombre","settings.uiLanguage":"Langue Interface","settings.learningLang":"Langue Apprise","settings.resetProgress":"R?initialiser","settings.dailyGoal":"Objectif XP","settings.currentMembership":"Abonnement Actuel","settings.premium":"Premium","settings.free":"Gratuit","settings.manage":"G?rer","settings.upgrade":"Am?liorer","settings.thisWeek":"Cette Semaine","settings.daysActive":"sur 7 jours actifs","settings.earned":"Gagn?!","settings.never":"Jamais","settings.demoMode":"(D?mo) configuration stock?e dans localStorage — d?ployer sur Vercel pour un vrai d?ploiement.","settings.aiModel":"Mod?le IA","settings.paypalClientID":"Ko-fi Client ID","settings.paypalPublic":"(public)","settings.onlySetting":"C'est le SEUL param?tre dont vous avez besoin.","settings.saveConfig":"Sauvegarder","settings.saved":"✅ Sauvegard?!","settings.savedNote":"✅ Aucune cl? API dans le navigateur ou GitHub.","settings.deployNote":"D?ployez sur Vercel, d?finissez les var. d'environnement.","settings.currentEmail":"Email actuel","settings.newEmail":"Nouveau email","settings.emailConfirm":"Mot de passe actuel (pour confirmer)","settings.updateEmail":"Mettre ? jour","settings.loginPrompt":"(D?mo — seuls les utilisateurs connect?s apparaissent pour cet email.)","settings.resetWarning":"Cela r?initialise vos XP, niveau et s?rie ? z?ro. Votre compte et param?tres restent.","settings.resetConfirm":"R?initialiser tout le progr?s ? Ceci est irr?versible.","settings.resetAllProgress":"R?initialiser Tout","settings.defaultGoal":"Par d?faut : 50 XP. Des objectifs personnalis?s seront disponibles bientÃ´t.","settings.memberSince":"Membre depuis","settings.accountInfo":"Vous pouvez modifier votre email ou mot de passe ici.",
  "nav.home":"Accueil","nav.profile":"Profil","nav.grammar":"Grammaire","nav.words":"Mots","nav.tests":"Tests","nav.practice":"Pratique","nav.mistakes":"Erreurs","nav.ai_chat":"IA Chat",
  "generic.back_dashboard":"Retour","generic.cancel":"Annuler","generic.save":"Sauver","generic.loading":"Chargement...",
  "placeholder.email":"vous@exemple.fr","placeholder.username":"nom","placeholder.password":"Min. 6","placeholder.confirmPassword":"Confirmer","placeholder.identifier":"nom ou email","placeholder.passwordLogin":"Mot de passe",
};
const de: Dict = {
  "topbar.level":"Level","topbar.xp":"EP","topbar.logout":"Abmelden","topbar.streak":"Tage","topbar.uiLanguage":"OberflÃ¤che",
  "login.title":"Willkommen","login.subtitle":"Melde dich an","login.identifier":"Benutzername oder E-Mail","login.password":"Passwort","login.forgotPassword":"Passwort vergessen?","login.rememberMe":"Angemeldet bleiben","login.submit":"Anmelden","login.noAccount":"Kein Konto?","login.createAccount":"Erstellen","login.errorEmpty":"Alle Felder ausf?llen.","login.errorInvalid":"Ung?ltig.","login.errorGeneral":"Fehler.","login.forgotMsg":"Neues Konto erstellen.",
  "register.title":"Konto erstellen","register.subtitle":"Heute lernen","register.email":"E-Mail","register.username":"Benutzername","register.password":"Passwort","register.confirmPassword":"BestÃ¤tigen","register.submit":"Registrieren","register.hasAccount":"Schon Konto?","register.loginLink":"Anmelden","register.errorEmailRequired":"E-Mail n?tig.","register.errorEmailFormat":"G?ltige E-Mail.","register.errorUsernameRequired":"Name n?tig.","register.errorUsernameShort":"Min. 3 Zeichen.","register.errorUsernameChars":"Nur Buchstaben/Zahlen.","register.errorPasswordRequired":"Passwort n?tig.","register.errorPasswordShort":"Min. 6 Zeichen.","register.errorConfirmRequired":"BestÃ¤tigen.","register.errorConfirmMatch":"Stimmt nicht ?berein.","register.errorEmailExists":"E-Mail existiert.","register.errorUsernameTaken":"Name vergeben.",
  "dashboard.welcome":"Willkommen,","dashboard.noLanguagePrompt":"WÃ¤hle eine Sprache!","dashboard.learningLanguage":"Lernen","dashboard.level":"Level","dashboard.totalXP":"Gesamt-EP","dashboard.streak":"Streak","dashboard.days":"Tage","dashboard.language":"Sprache","dashboard.none":"Keine","dashboard.xpProgress":"Fortschritt","dashboard.needMoreXP":"Brauchst","dashboard.moreXP":"EP mehr","dashboard.dailyGoal":"Tagesziel","dashboard.dailyGoalReached":"Ziel erreicht!","dashboard.dailyGoalEmpty":"Mach eine Ãœbung!","dashboard.continueLearning":"Weiterlernen","dashboard.chooseLanguage":"WÃ¤hle Sprache","dashboard.streakActive":"Tage! Weiter!","dashboard.streakAtRisk":"Nicht verlieren!","dashboard.emptyStreak":"Starte heute!",
  "dashboard.legend":"Legende","dashboard.legendSub":"Season-Levels. Freischalten, spielen, EP verdienen.","dashboard.grammarBtn":"Grammatik","dashboard.grammarBtnSub":"Schritt-f?r-Schritt Grammatiklektionen mit Ãœbungen.","dashboard.mistakeBtn":"Fehler Review","dashboard.mistakeBtnSub":"Lerne aus Fehlern & verbessere dich.","dashboard.testBtn":"Tests & Quiz","dashboard.testSub":"Fordere dich selbst heraus!","dashboard.arenaBtnSub":"Season-Levels. Freischalten, spielen, EP verdienen.","dashboard.wotdBtn":"Wort des Tages","dashboard.wotdBtnSub":"Lerne tÃ¤glich ein neues Wort.","dashboard.7dayChampion":"🏆 7-Tage-Champion","dashboard.streak7dayBadge":"⭐ 7-Tage-Streak","dashboard.continueIn":"Genau da weitermachen, wo du aufgeh?rt hast","dashboard.continueInLang":"Weitermachen in","dashboard.milestone30":"30-Tage-Champion","dashboard.milestone7":"7-Tage-Streak",
  "lang.en":"Englisch","lang.nl":"NiederlÃ¤ndisch","lang.fr":"Franz?sisch","lang.de":"Deutsch","lang.es":"Spanisch",
  "wotd.title":"Wort des Tages","wotd.i_know":"Ich weiÃŸ es","wotd.show_hint":"Hinweis?","wotd.dont_know":"WeiÃŸ nicht","wotd.learned":"Gelernt!","wotd.back_tomorrow":"Morgen wiederkommen","wotd.all_done":"Fertig!","wotd.all_done_msg":"Heute schon ge?bt.","wotd.review":"Wiederholen","wotd.words_learned":"W?rter gelernt","wotd.youre_done":"Fertig","wotd.see_tomorrow":"Bis morgen!",
  "grammar.title":"Grammatik","grammar.back_lessons":"Zur?ck","grammar.learn":"Lernen","grammar.test":"Test","grammar.test_coming":"Test bald","grammar.mark_complete":"AbschlieÃŸen","grammar.completed":"Abgeschlossen","grammar.search":"Suchen...","grammar.no_match":"Nichts gefunden.","grammar.exercises_title":"Ãœbungen",
  "grammar.overview":"Was du lernst","grammar.build":"Was du bauen kannst","grammar.conjugation":"Konjugation","grammar.rules":"Grammatikregeln","grammar.time_expr":"Zeitausdr?cke","grammar.details":"Detaillierte ErklÃ¤rung","grammar.callouts":"Wichtige Punkte","grammar.mistakes_title":"HÃ¤ufige Fehler","grammar.review":"Schnelle Wiederholung","grammar.qa":"Ãœbungsfragen",
  "vocab.title":"Wortschatz","vocab.back":"Zur?ck","vocab.mark_learned":"Gelernt markieren","vocab.learned":"Gelernt","vocab.search":"Suchen...","vocab.example":"Beispiel","vocab.progress":"gelernt",
  "tests.title":"Tests & Quiz","tests.back":"Zur?ck","tests.search":"Suchen...","tests.pass":"Bestehen","tests.questions":"Fragen","tests.passed":"Bestanden!","tests.keep_practicing":"Weiter ?ben!","tests.score":"Punktzahl","tests.xp_earned":"EP","tests.submit":"Abgeben","tests.previous":"Zur?ck","tests.next":"Weiter",
  "exercise.title":"Ãœbungsmodus","exercise.subtitle":"Thema wÃ¤hlen.","exercise.all_topics":"Alle","exercise.correct":"Richtig!","exercise.wrong":"Falsch. Antwort:","exercise.no_penalty":"Keine Strafe!","exercise.next_question":"NÃ¤chste","exercise.see_results":"Ergebnisse","exercise.new_session":"Neue Session","exercise.complete":"Fertig!","exercise.accuracy":"Genauigkeit","exercise.earned":"EP verdient",
  "mistakes.title":"Fehler Review","mistakes.subtitle":"Lerne aus Fehlern","mistakes.search":"Suchen...","mistakes.no_mistakes":"Keine Fehler!","mistakes.no_mistakes_msg":"Fehler erscheinen hier.","mistakes.no_match":"Keine","mistakes.total":"Gesamt","mistakes.unreviewed":"Ungesehen","mistakes.reviewed":"Gesehen","mistakes.review":"Als gesehen","mistakes.delete":"L?schen","mistakes.clear_all":"Alle l?schen","mistakes.question":"Frage","mistakes.your_answer":"Deine Antwort","mistakes.correct_answer":"Richtige Antwort","mistakes.practice_again":"Nochmal","mistakes.source_exercise":"Ãœbung","mistakes.source_test":"Test",
  "ai.title":"KI Tutor","ai.premium_ul":"Premium — unbegrenzt","ai.paywall":"Zahlung n?tig","ai.unlock_btn":"EUR 4.00 / 30 days via Ko-fi","ai.unlock_title":"KI Tutor freischalten","ai.unlock_desc":"Unbegrenzte KI Grammatik, Ãœbersetzung, Konversation.","ai.grammar_feat":"Grammatik Hilfe","ai.translate_feat":"Alles ?bersetzen","ai.convo_feat":"Konversation ?ben","ai.claude_feat":"Von Claude AI","ai.grammar_mode":"Grammatik","ai.translate_mode":"Ãœbersetzung","ai.convo_mode":"Konversation","ai.grammar_desc":"Grammatik fragen","ai.translate_desc":"SÃ¤tze ?bersetzen","ai.convo_desc":"Nat?rlich sprechen","ai.powered_by":"von Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Sicheres Ko-fi",
  "profile.member_since":"Mitglied seit","profile.learning_langs":"Sprachen","profile.earned":"Verdient!","profile.membership":"Mitgliedschaft","profile.premium_member":"Premium","profile.free_plan":"Kostenlos","profile.manage":"Verwalten","profile.upgrade":"Upgrade","profile.currently_learning":"Aktiv","profile.active":"Aktiv","profile.premiumStatus":"{role} — Unbegrenzt KI, ohne Werbung","profile.freeStatus":"5 KI-Nachrichten/Tag, Werbung & Basisfunktionen","profile.quickLinks":"Quick Links","profile.settings":"Einstellungen","profile.totalXP":"Gesamt-EP","profile.levelStat":"Level","profile.currentStreak":"Aktuelle Streak","profile.longestStreak":"LÃ¤ngste Streak","profile.levelProgress":"Level Fortschritt","profile.xpToNext":"{xpCurrent} / {xpNeeded} EP → Level {nextLevel}","profile.thisWeek":"Diese Woche","profile.daysActiveThisWeek":"{activeDays} von 7 Tagen aktiv","profile.achievements":"Errungenschaften","profile.sevenDayStreak":"🔥 7-Tage-Streak","profile.thirtyDayStreak":"🏆 30-Tage-Streak","profile.firstLesson":"⭐ Erste Lektion","profile.goalCrusher":"🎯 Goal Crusher","profile.scholar":"📚 Scholar","profile.xpWarrior":"💪 XP Krieger","profile.backToDashboard":"Zur?ck",
  "settings.title":"Einstellungen","settings.back":"Zur?ck","settings.account":"Konto","settings.preferences":"PrÃ¤ferenzen","settings.learning":"Lernen","settings.ai_tab":"KI","settings.changeEmail":"E-Mail Ã„ndern","settings.changePassword":"Passwort Ã„ndern","settings.deleteAccount":"Konto L?schen","settings.theme":"Design","settings.light":"Hell","settings.dark":"Dunkel","settings.uiLanguage":"OberflÃ¤che","settings.learningLang":"Lernsprache","settings.resetProgress":"Fortschritt L?schen","settings.dailyGoal":"Tagesziel","settings.currentMembership":"Mitgliedschaft","settings.premium":"Premium","settings.free":"Kostenlos","settings.manage":"Verwalten","settings.upgrade":"Upgrade","settings.thisWeek":"Diese Woche","settings.daysActive":"von 7 Tagen aktiv","settings.earned":"Verdient!","settings.never":"Nie","settings.demoMode":"(Demo) Konfiguration in localStorage gespeichert — f?r echte Bereitstellung zu Vercel wechseln.","settings.aiModel":"KI Modell","settings.paypalClientID":"Ko-fi Client ID","settings.paypalPublic":"(Ã–ffentlich)","settings.onlySetting":"Dies ist die EINZIGE Einstellung die Sie brauchen.","settings.saveConfig":"Speichern","settings.saved":"✅ Gespeichert!","settings.savedNote":"✅ Keine API-Schl?ssel im Browser oder auf GitHub.","settings.deployNote":"Zu Vercel deployen, Umgebungsvariablen im Dashboard setzen.","settings.currentEmail":"Aktuelle E-Mail","settings.newEmail":"Neue E-Mail","settings.emailConfirm":"Aktuelles Passwort (zur BestÃ¤tigung)","settings.updateEmail":"E-Mail Aktualisieren","settings.loginPrompt":"(Demo — nur eingeloggte Benutzer erscheinen f?r diese E-Mail.)","settings.resetWarning":"Dies setzt deine EP, dein Level und deine Streak auf 0 zur?ck. Konto und Einstellungen bleiben.","settings.resetConfirm":"Gesamten Lernfortschritt zur?cksetzen? Dies kann nicht r?ckgÃ¤ngig gemacht werden.","settings.resetAllProgress":"Alles Zur?cksetzen","settings.defaultGoal":"Standard: 50 EP. Benutzerdefinierte Ziele in zuk?nftigen Updates.","settings.memberSince":"Mitglied seit","settings.accountInfo":"Du kannst hier deine E-Mail oder dein Passwort Ã¤ndern.",
  "nav.home":"Start","nav.profile":"Profil","nav.grammar":"Grammatik","nav.words":"W?rter","nav.tests":"Tests","nav.practice":"Ãœben","nav.mistakes":"Fehler","nav.ai_chat":"KI Chat",
  "generic.back_dashboard":"Zur?ck","generic.cancel":"Abbrechen","generic.save":"Speichern","generic.loading":"LÃ¤dt...",
  "placeholder.email":"du@beispiel.de","placeholder.username":"name","placeholder.password":"Min. 6","placeholder.confirmPassword":"BestÃ¤tigen","placeholder.identifier":"name oder email","placeholder.passwordLogin":"Passwort",
};
const es: Dict = {
  "topbar.level":"Nivel","topbar.xp":"PX","topbar.logout":"Salir","topbar.streak":"dÃ­as","topbar.uiLanguage":"Idioma",
  "login.title":"Bienvenido","login.subtitle":"Inicia sesiÃ³n","login.identifier":"Usuario o email","login.password":"Contrase?a","login.forgotPassword":"?Olvidaste?","login.rememberMe":"Recordarme","login.submit":"Entrar","login.noAccount":"?Sin cuenta?","login.createAccount":"Crear una","login.errorEmpty":"Completa todos.","login.errorInvalid":"InvÃ¡lido.","login.errorGeneral":"Error.","login.forgotMsg":"Crea nueva cuenta si olvidaste.",
  "register.title":"Crear cuenta","register.subtitle":"Empieza hoy","register.email":"Email","register.username":"Usuario","register.password":"Contrase?a","register.confirmPassword":"Confirmar","register.submit":"Registrar","register.hasAccount":"?Ya tienes?","register.loginLink":"Entrar","register.errorEmailRequired":"Email necesario.","register.errorEmailFormat":"Email vÃ¡lido.","register.errorUsernameRequired":"Usuario necesario.","register.errorUsernameShort":"MÃ­n. 3 caracteres.","register.errorUsernameChars":"Letras, nÃºmeros, guiones.","register.errorPasswordRequired":"Contrase?a necesaria.","register.errorPasswordShort":"MÃ­n. 6 caracteres.","register.errorConfirmRequired":"Confirma.","register.errorConfirmMatch":"No coinciden.","register.errorEmailExists":"Email ya existe.","register.errorUsernameTaken":"Usuario ya tomado.",
  "dashboard.welcome":"?Bienvenido,","dashboard.noLanguagePrompt":"?Elige un idioma!","dashboard.learningLanguage":"Aprendiendo","dashboard.level":"Nivel","dashboard.totalXP":"PX Total","dashboard.streak":"Racha","dashboard.days":"dÃ­as","dashboard.language":"Idioma","dashboard.none":"Ninguno","dashboard.xpProgress":"Progreso","dashboard.needMoreXP":"Necesitas","dashboard.moreXP":"PX mÃ¡s","dashboard.dailyGoal":"Objetivo","dashboard.dailyGoalReached":"?Objetivo!","dashboard.dailyGoalEmpty":"?Haz ejercicio!","dashboard.continueLearning":"Continuar","dashboard.chooseLanguage":"Elige idioma","dashboard.streakActive":"dÃ­as! ?Sigue!","dashboard.streakAtRisk":"?No pierdas!","dashboard.emptyStreak":"?Empieza hoy!",
  "dashboard.legend":"Leyenda","dashboard.legendSub":"Niveles de temporada. Desbloquea, juega, gana XP.","dashboard.grammarBtn":"Gram?tica","dashboard.grammarBtnSub":"GuÃ­as de gramÃ¡tica paso a paso con ejercicios.","dashboard.mistakeBtn":"Errores","dashboard.mistakeBtnSub":"Aprende de tus errores y mejora.","dashboard.testBtn":"Pruebas","dashboard.testSub":"?Ponte a prueba!","dashboard.arenaBtnSub":"Niveles de temporada. Desbloquea, juega, gana XP.","dashboard.wotdBtn":"Palabra del D?a","dashboard.wotdBtnSub":"Aprende una palabra nueva cada dÃ­a.","dashboard.7dayChampion":"🏆 CampeÃ³n de 7 dÃ­as","dashboard.streak7dayBadge":"⭐ Racha de 7 dÃ­as","dashboard.continueIn":"ContinÃºa exactamente donde lo dejaste","dashboard.continueInLang":"ContinÃºa en","dashboard.milestone30":"CampeÃ³n de 30 dÃ­as","dashboard.milestone7":"Racha de 7 dÃ­as",
  "lang.en":"Ingl?s","lang.nl":"Neerland?s","lang.fr":"Franc?s","lang.de":"AlemÃ¡n","lang.es":"Español",
  "wotd.title":"Palabra del D?a","wotd.i_know":"La s?","wotd.show_hint":"?Pista?","wotd.dont_know":"No la s?","wotd.learned":"?Aprendida!","wotd.back_tomorrow":"Vuelve ma?ana","wotd.all_done":"?Terminado!","wotd.all_done_msg":"Ya has practicado hoy.","wotd.review":"Repasar","wotd.words_learned":"palabras aprendidas","wotd.youre_done":"Terminado","wotd.see_tomorrow":"?Hasta ma?ana!",
  "grammar.title":"Gram?tica","grammar.back_lessons":"Volver","grammar.learn":"Aprender","grammar.test":"Prueba","grammar.test_coming":"Prueba pronto","grammar.mark_complete":"Completar","grammar.completed":"Completado","grammar.search":"Buscar...","grammar.no_match":"Sin resultados.","grammar.exercises_title":"Ejercicios",
  "grammar.overview":"Lo que aprenderÃ¡s","grammar.build":"Lo que puedes construir","grammar.conjugation":"ConjugaciÃ³n","grammar.rules":"Reglas de gramÃ¡tica","grammar.time_expr":"Expresiones de tiempo","grammar.details":"ExplicaciÃ³n detallada","grammar.callouts":"Puntos importantes","grammar.mistakes_title":"Errores comunes","grammar.review":"RevisiÃ³n rÃ¡pida","grammar.qa":"Preguntas de prÃ¡ctica",
  "vocab.title":"Vocabulario","vocab.back":"Volver","vocab.mark_learned":"Marcar aprendida","vocab.learned":"Aprendida","vocab.search":"Buscar...","vocab.example":"Ejemplo","vocab.progress":"aprendidas",
  "tests.title":"Pruebas","tests.back":"Volver","tests.search":"Buscar...","tests.pass":"Aprobar","tests.questions":"preguntas","tests.passed":"?Aprobado!","tests.keep_practicing":"?Sigue!","tests.score":"Puntaje","tests.xp_earned":"PX","tests.submit":"Entregar","tests.previous":"Anterior","tests.next":"Siguiente",
  "exercise.title":"PrÃ¡ctica","exercise.subtitle":"Elige un tema.","exercise.all_topics":"Todos","exercise.correct":"?Correcto!","exercise.wrong":"Mal. Respuesta:","exercise.no_penalty":"?Sin penalizaciÃ³n!","exercise.next_question":"Siguiente","exercise.see_results":"Resultados","exercise.new_session":"Nueva SesiÃ³n","exercise.complete":"?Completo!","exercise.accuracy":"precisiÃ³n","exercise.earned":"PX ganados",
  "mistakes.title":"Revisar Errores","mistakes.subtitle":"Aprende de tus errores","mistakes.search":"Buscar...","mistakes.no_mistakes":"?Sin errores!","mistakes.no_mistakes_msg":"Errores aparecerÃ¡n aquÃ­.","mistakes.no_match":"Nada","mistakes.total":"Total","mistakes.unreviewed":"No vistos","mistakes.reviewed":"Vistos","mistakes.review":"Marcar visto","mistakes.delete":"Borrar","mistakes.clear_all":"Borrar todo","mistakes.question":"Pregunta","mistakes.your_answer":"Tu Respuesta","mistakes.correct_answer":"Correcta","mistakes.practice_again":"Otra vez","mistakes.source_exercise":"Ejercicio","mistakes.source_test":"Prueba",
  "ai.title":"Tutor IA","ai.premium_ul":"Premium — ilimitado","ai.paywall":"Pago necesario","ai.unlock_btn":"EUR 4.00 / 30 days via Ko-fi","ai.unlock_title":"Desbloquear Tutor IA","ai.unlock_desc":"Gram?tica, traducciÃ³n y conversaci?n ilimitadas.","ai.grammar_feat":"Gram?tica","ai.translate_feat":"Traducci?n","ai.convo_feat":"ConversaciÃ³n","ai.claude_feat":"Por Claude AI","ai.grammar_mode":"Gram?tica","ai.translate_mode":"Traducci?n","ai.convo_mode":"ConversaciÃ³n","ai.grammar_desc":"Reglas gramaticales","ai.translate_desc":"Traducir frases","ai.convo_desc":"Hablar naturalmente","ai.powered_by":"por Claude","ai.premium_footer":"Premium — Claude AI","ai.secure":"Ko-fi seguro",
  "profile.member_since":"Miembro desde","profile.learning_langs":"Idiomas","profile.earned":"?Ganado!","profile.membership":"MembresÃ­a","profile.premium_member":"Premium","profile.free_plan":"Gratis","profile.manage":"Gestionar","profile.upgrade":"Mejorar","profile.currently_learning":"Activo","profile.active":"Activo","profile.premiumStatus":"{role} — IA ilimitada, sin anuncios","profile.freeStatus":"5 mensajes IA/dÃ­a, anuncios & funciones bÃ¡sicas","profile.quickLinks":"Enlaces RÃ¡pidos","profile.settings":"Ajustes","profile.totalXP":"PX Total","profile.levelStat":"Nivel","profile.currentStreak":"Racha Actual","profile.longestStreak":"Racha MÃ¡s Larga","profile.levelProgress":"Progreso de Nivel","profile.xpToNext":"{xpCurrent} / {xpNeeded} PX → Nivel {nextLevel}","profile.thisWeek":"Esta Semana","profile.daysActiveThisWeek":"{activeDays} de 7 dÃ­as activos","profile.achievements":"Logros","profile.sevenDayStreak":"🔥 Racha de 7 D?as","profile.thirtyDayStreak":"🏆 Racha de 30 D?as","profile.firstLesson":"⭐ Primera LecciÃ³n","profile.goalCrusher":"🎯 Goal Crusher","profile.scholar":"📚 Scholar","profile.xpWarrior":"💪 Guerrero XP","profile.backToDashboard":"Volver",
  "settings.title":"Ajustes","settings.back":"Volver","settings.account":"Cuenta","settings.preferences":"Preferencias","settings.learning":"Aprendizaje","settings.ai_tab":"IA","settings.changeEmail":"Cambiar Email","settings.changePassword":"Cambiar Contrase?a","settings.deleteAccount":"Borrar Cuenta","settings.theme":"Tema","settings.light":"Claro","settings.dark":"Oscuro","settings.uiLanguage":"Idioma","settings.learningLang":"Idioma de Aprendizaje","settings.resetProgress":"Reiniciar","settings.dailyGoal":"Objetivo XP","settings.currentMembership":"MembresÃ­a","settings.premium":"Premium","settings.free":"Gratis","settings.manage":"Gestionar","settings.upgrade":"Mejorar","settings.thisWeek":"Esta Semana","settings.daysActive":"de 7 dÃ­as activos","settings.earned":"?Ganado!","settings.never":"Nunca","settings.demoMode":"(Demo) config almacenada en localStorage — despliega en Vercel.","settings.aiModel":"Modelo IA","settings.paypalClientID":"Ko-fi Client ID","settings.paypalPublic":"(pÃºblico)","settings.onlySetting":"Este es el ÃšNICO ajuste que necesitas.","settings.saveConfig":"Guardar","settings.saved":"✅ Guardado!","settings.savedNote":"✅ Sin claves API en el navegador o GitHub.","settings.deployNote":"Despliega en Vercel, configura variables de entorno.","settings.currentEmail":"Email actual","settings.newEmail":"Nuevo email","settings.emailConfirm":"Contrase?a actual (para confirmar)","settings.updateEmail":"Actualizar Email","settings.loginPrompt":"(Demo — solo usuarios conectados aparecen para este email.)","settings.resetWarning":"Esto reinicia tus XP, nivel y racha a cero. Tu cuenta y ajustes se mantienen.","settings.resetConfirm":"?Reiniciar todo el progreso? Esto no se puede deshacer.","settings.resetAllProgress":"Reiniciar Todo","settings.defaultGoal":"Por defecto: 50 XP. Objetivos personalizados prÃ³ximamente.","settings.memberSince":"Miembro desde","settings.accountInfo":"Puedes cambiar tu email o contrase?a aquÃ­.",
  "nav.home":"Inicio","nav.profile":"Perfil","nav.grammar":"Gram?tica","nav.words":"Palabras","nav.tests":"Pruebas","nav.practice":"PrÃ¡ctica","nav.mistakes":"Errores","nav.ai_chat":"Chat IA",
  "generic.back_dashboard":"Volver","generic.cancel":"Cancelar","generic.save":"Guardar","generic.loading":"Cargando...",
  "placeholder.email":"tu@ejemplo.es","placeholder.username":"usuario","placeholder.password":"MÃ­n. 6","placeholder.confirmPassword":"Confirmar","placeholder.identifier":"usuario o email","placeholder.passwordLogin":"Contrase?a",
};

const all: Record<string, Dict> = { en, nl, fr, de, es };
export type TranslationKey = keyof typeof en;

export function getTranslation(lang: UILanguage, key: TranslationKey): string {
  const dict = all[lang] ?? en;
  return dict[key as string] ?? en[key as string] ?? key;
}

export function getTranslations(lang: UILanguage): Dict {
  return all[lang] ?? en;
}
