import type { GrammarLesson } from "../../types";
import type { GrammarLessonMeta } from "../lazy";

type NlGrammarRow = readonly [id: string, title: string, level: number, topic: string, file: string, exportName: string];

const rows: NlGrammarRow[] = [
  ["nl-uitspraak-1","Uitspraak & Klanken: De Ultieme Visuele Gids",1,"Uitspraak","uitspraak","uitspraak"],
  ["nl-voorstellen-1","Zich voorstellen: naam, leeftijd, woonplaats, nationaliteit",1,"Pragmatiek","voorstellen","voorstellen"],
  ["nl-groeten-1","Groeten en afscheid nemen (formeel/informeel)",1,"Presentatie & Vocabulaire","groeten","groeten"],
  ["nl-cijfers-1","Cijfers, Getallen en Datum",1,"Vocabulaire","cijfersGetallen","cijfersGetallen"],
  ["nl-kleuren-1","Kleuren en Eenvoudige Beschrijvingen",1,"Vocabulaire","kleuren","kleuren"],
  ["nl-familie-1","Familie en Relaties",1,"Vocabulaire","familie","familie"],
  ["nl-routines-1","Dagelijkse Routines en Klokkijken",1,"Vocabulaire & Presentatie","routines","routines"],
  ["nl-boodschappen-1","Boodschappen Doen",1,"Presentatie & Vocabulaire","boodschappen","boodschappen"],
  ["nl-cafe-1","In een Café of Restaurant",1,"Presentatie","cafe","cafe"],
  ["nl-wegvragen-1","De weg vragen en wijzen",1,"Pragmatiek","wegVragen","wegVragen"],
  ["nl-formulieren-1","Eenvoudige formulieren invullen",1,"Formulieren","formulieren","formulieren"],
  ["nl-lidwoorden-1","Lidwoorden: De, Het, Een, Geen & Het Nul‑lidwoord",1,"Grammatica","lidwoorden","lidwoorden"],
  ["nl-zelfstandignaamwoord-1","Het Zelfstandig Naamwoord: Soorten en Geslacht",1,"Gramamatica","zelfstandigNaamwoord","zelfstandigNaamwoord"],
  ["nl-verwijswoorden-1","Verwijswoorden: hij/zij/het, deze/die/dit/dat",1,"Grammatica","verwijswoorden","verwijswoorden"],
  ["nl-meervoud-1","Meervoud van Zelfstandige Naamwoorden: -en, -s, -eren en Onregelmatig",1,"Gammatica","meervoud","meervoud"],
  ["nl-persoonlijkevoornaamwoorden-onderwerp-1","Persoonlijke Voornaamwoorden (Onderwerp): ik, jij, u, hij, zij, het, wij, jullie, zij",1,"Persoonlijke voornaamwoorden (onderwerp)","persoonlijkeVoornaamwoordenOnderwerp","persoonlijkeVoornaamwoordenOnderwerp"],
  ["nl-persoonlijkevoornaamwoorden-object-1","Persoonlijke Voornaamwoorden (Object): mij, jou, u, hem, haar, het, ons, jullie, hen/hun",1,"Persoonlijke voornaamwoorden (object)","persoonlijkeVoornaamwoordenObject","persoonlijkeVoornaamwoordenObject"],
  ["nl-gereduceerdevormen-1","Gereduceerde Vormen: 'k, je, 'ie, 't – Informele Persoonlijke Voornaamwoorden",1,"Gereduceerde vormen","gereduceerdevormen","gereduceerdevormen"],
  ["nl-bezittelijkeVoornaamwoorden-1","Bezittelijke Voornaamwoorden: mijn, jouw, uw, zijn, haar, ons/onze, jullie, hun",1,"Bezittelijke voornaamwoorden","bezittelijkeVoornaamwoorden","bezittelijkeVoornaamwoorden"],
  ["nl-aanwijzendeVoornaamwoorden-1","Aanwijzende Voornaamwoorden: deze/die & dit/dat",1,"Aanwijzende voornaamwoorden","aanwijzendeVoornaamwoorden","aanwijzendeVoornaamwoorden"],
  ["nl-onbepaaldeVoornaamwoorden-1","Onbepaalde Voornaamwoorden: iemand, niemand, men, je, iets, niets, alles",1,"Onbepaalde voornaamwoorden","onbepaaldeVoornaamwoorden","onbepaaldeVoornaamwoorden"],
  ["nl-hoofdtelwoorden-1","Hoofdtelwoorden: één, twee, drie en verder...",1,"Hoofdtelwoorden","hoofdtelwoorden","hoofdtelwoorden"],
  ["nl-rangtelwoorden-1","Rangtelwoorden: eerste, tweede, derde en verder...",1,"Rangtelwoorden","rangtelwoorden","rangtelwoorden"],
  ["nl-voorzetsels-1","Voorzetsels: in, op, onder, naast, voor, achter, bij, tussen en meer",1,"Voorzetsels","voorzetsels","voorzetsels"],
  ["nl-bijwoorden-1","Bijwoorden van Tijd, Plaats, Wijze, Hoeveelheid en Houding",1,"Bijwoorden","bijwoorden","bijwoorden"],
  ["nl-infinitief-stam-ikvorm-1","Infinitief, Stam en Ik-vorm",1,"Infinitief, stam en ik-vorm","infinitiefStamIkvorm","infinitiefStamIkvorm"],
  ["nl-tegenwoordigetijd-1","Tegenwoordige Tijd: stam+t – ik werk, jij werkt, hij werkt",1,"Tegenwoordige tijd","tegenwoordigeTijd","tegenwoordigeTijd"],
  ["nl-ovt-1","Onvoltooid Verleden Tijd (OVT): Zwak, Sterk en Onregelmatig",1,"Onvoltooid Verleden Tijd","ovt","ovt"],
  ["nl-gebiedendewijs-1","Gebiedende Wijs: Loop! – Loopt u! – Laten we...",1,"Gebiedende wijs","gebiedendeWijs","gebiedendeWijs"],
  ["nl-hoofdzin-mededelend-1","De Hoofdzin – Mededelend (SVO-volgorde): Jan leest het boek",1,"Hoofdzin (mededelend)","hoofdzinMededelend","hoofdzinMededelend"],
  ["nl-vraagzinnen-janee-1","Vraagzinnen – Ja/Nee-vragen: Heb jij dat gedaan?",1,"Vraagzinnen (ja/nee)","vraagzinnenjanee","vraagzinnenjanee"],
  ["nl-vraagzinnen-vraagwoord-1","Vraagzinnen met een Vraagwoord: Wie, Wat, Waar, Wanneer, Waarom, Hoe",1,"Vraagzinnen (vraagwoord)","vraagzinnenVraagwoord","vraagzinnenVraagwoord"],
  ["nl-ontkenning-niet-1","Ontkenning met 'niet' – Plaats in hoofdzin en bijzin",1,"Ontkenning (niet)","ontkenningNiet","ontkenningNiet"],
  ["nl-ontkenning-geen-1","Ontkenning met 'geen' – Plaatsing en gebruik",1,"Ontkenning (geen)","ontkenningGeen","ontkenningGeen"],
  ["nl-persoonsvorm-1","De Persoonsvorm (PV) – De werkwoordsvorm die met het onderwerp congrueert",1,"Persoonsvorm (congruentie)","persoonsvorm","persoonsvorm"],
  ["nl-onderwerp-1","Het Onderwerp (OW) – Wie of wat + persoonsvorm?",1,"Onderwerp","onderwerp","onderwerp"],
  ["nl-luisteren-station-1","Luistervaardigheid: Korte Dialogen en Mededelingen op het Station",1,"Luisteren – Station","luisterenStation","luisterenStation"],
  ["nl-leesvaardigheid-advertenties-1","Leesvaardigheid: Eenvoudige Advertenties, Menukaarten en Bordjes",1,"Lezen – Advertenties, menukaarten, bordjes","leesvaardigheidAdvertenties","leesvaardigheidAdvertenties"],
  ["nl-schrijfvaardigheid-bericht-1","Schrijfvaardigheid: Een Kort Berichtje, E‑mail aan een Vriend",1,"Schrijven – Bericht en e-mail","schrijfvaardigheidBericht","schrijfvaardigheidBericht"],
  ["nl-spreekvaardigheid-voorstellen-1","Spreekvaardigheid: Jezelf Voorstellen en Simpele Vragen Stellen",1,"Spreken – Jezelf voorstellen","spreekvaardigheidVoorstellen","spreekvaardigheidVoorstellen"],
  ["nl-feestdagen-1","Nederlandse en Belgische Feestdagen en Gewoontes",1,"Feestdagen en gewoontes","feestdagen","feestdagen"],
  ["nl-zelfevaluatie-a1-1","Zelfevaluatie A1 – Checklist: Wat kun je al?",1,"Zelfevaluatie A1","zelfevaluatieA1","zelfevaluatieA1"],
  ["nl-belangrijke-werkwoorden-1","Belangrijkste Nederlandse Werkwoorden",1,"Werkwoorden – Essentieel","belangrijkeWerkwoorden","belangrijkeWerkwoorden"],
  ["nl-hoofdletters-1","Hoofdletters: Eigennamen, Titels, Aardrijkskundige Namen en Meer",2,"Hoofdletters","hoofdletters","hoofdletters"],
  ["nl-kleineletters-1","Kleine Letters: Samenstellingen, Afleidingen, Dagen en Maanden",2,"Kleine letters","kleineletters","kleineletters"],
  ["nl-accenttekens-1","Accenttekens: Nadruk, Uitspraak, Betekenisonderscheid en Trema",2,"Accenttekens","accenttekens","accenttekens"],
  ["nl-trema-apostrof-1","Trema en Apostrof – Klinkerbotsing, Meervoud en Weglating",2,"Trema en apostrof","tremaApostrof","tremaApostrof"],
  ["nl-koppelteken-1","Het Koppelteken – Samenstellingen, Samenkoppelingen en Meer",2,"Koppelteken","koppelteken","koppelteken"],
  ["nl-leestekens-1","Leestekens: Punt, Komma, Puntkomma en Dubbele Punt",2,"Leestekens","leestekens","leestekens"],
  ["nl-tussenklanken-1","Tussenklanken in Samenstellingen: -n-, -s-, -e-",2,"Tussenklanken","tussenklanken","tussenklanken"],
  ["nl-aaneenschrijven-1","Aaneenschrijven of Los? – Samenstellingen, Werkwoorden en Vaste Combinaties",2,"Aaneenschrijven of los","aaneenschrijvenOfLos","aaneenschrijvenOfLos"],
  ["nl-telbaar-niet-telbaar-nominalisatie-1","Telbaar & Niet‑telbaar en Nominalisatie: meel, geld, het mooie, het lopen",2,"Telbaar en niet‑telbaar / Nominalisatie","telbaarNietTelbaarNominalisatie","telbaarNietTelbaarNominalisatie"],
  ["nl-bijvoeglijknaamwoord-1","Bijvoeglijk Naamwoord: Verbuiging en Stoffelijk Bijvoeglijk Naamwoord",2,"Bijvoeglijk naamwoord","bijvoeglijkNaamwoord","bijvoeglijkNaamwoord"],
  ["nl-trappen-van-vergelijking-1","Trappen van Vergelijking: Stellend, Vergrotend, Overtreffend en Als/Dan",2,"Trappen van vergelijking","trappenVanVergelijking","trappenVanVergelijking"],
  ["nl-zelfstandigbezittelijk-1","Zelfstandig Bezittelijk Voornaamwoord: de mijne, de jouwe, het onze...",2,"Bezittelijk voornaamwoord (zelfstandig)","zelfstandigBezittelijkVoornaamwoord","zelfstandigBezittelijkVoornaamwoord"],
  ["nl-wederkerendvnw-1","Het Wederkerend Voornaamwoord: me, je, zich, ons",2,"Wederkerend voornaamwoord","wederkerendVoornaamwoord","wederkerendVoornaamwoord"],
  ["nl-wederkerigvnw-1","Het Wederkerig Voornaamwoord: elkaar, mekaar, elkander",1,"Wederkerig voornaamwoord","wederkerigVoornaamwoord","wederkerigVoornaamwoord"],
  ["nl-breuken-getallen-1","Breuken, Getallen en Percentages",2,"Getallen en breuken","breukenGetallen","breukenGetallen"],
  ["nl-voorzetsels-tijd-plaats-2","Voorzetsels van Tijd en Plaats: Het Complete Overzicht",2,"Voorzetsels (tijd en plaats)","voorzetselsTijdPlaatsUitgebreid","voorzetselsTijdPlaatsUitgebreid"],
  ["nl-nevenschikkendevoegwoorden-1","Nevenschikkende Voegwoorden: en, maar, want, of, dus",2,"Voegwoorden (nevenschikkend)","nevenschikkendeVoegwoorden","nevenschikkendeVoegwoorden"],
  ["nl-onderschikkendevoegwoorden-1","Onderschikkende Voegwoorden: dat, omdat, toen, hoewel, als, zodat",2,"Voegwoorden (onderschikkend)","onderschikkendeVoegwoorden","onderschikkendeVoegwoorden"],
  ["nl-tkofschip-1","’t Kofschip – De Regel voor Zwakke Werkwoorden (-de of -te)",2,"’t Kofschip (spelling)","tKofschip","tKofschip"],
  ["nl-vtt-1","Voltooid Tegenwoordige Tijd (VTT): hebben/zijn + voltooid deelwoord",2,"Voltooid Tegenwoordige Tijd","vtt","vtt"],
  ["nl-ottt-zullen-2","Onvoltooid Toekomende Tijd (OTTt): zullen + infinitief & gaan + infinitief",2,"Toekomende tijd (zullen & gaan)","otttZullen","otttZullen"],
  ["nl-onvoltooiddeelwoord-1","Het Onvoltooid Deelwoord: lopend, werkend, zingend, slapend, denkend en meer",1,"Onvoltooid deelwoord","onvoltooidDeelwoord","onvoltooidDeelwoord"],
  ["nl-voltooiddeelwoord-2","Het Voltooid Deelwoord: gewerkt, geschreven, opgeruimd en nog veel meer",2,"Voltooid deelwoord","voltooidDeelwoord","voltooidDeelwoord"],
  ["nl-infinitiefmette-1","De Infinitief met 'te': Hij zit te lezen / Het is te doen",2,"Infinitief met te","infinitiefMetTe","infinitiefMetTe"],
  ["nl-kaleinfinitief-1","De Kale Infinitief: Wanneer géén 'te'? – Ik ga slapen, Hij kan zwemmen",2,"Kale infinitief","kaleInfinitief","kaleInfinitief"],
  ["nl-scheidbarewerkwoorden-1","Scheidbare Werkwoorden: Aankomen, Opbellen, Meenemen – De Complete Gids",2,"Scheidbare werkwoorden","scheidbareWerkwoorden","scheidbareWerkwoorden"],
  ["nl-werkwoordparen-1","Liggen/Leggen, Zitten/Zetten, Staan/Stellen, Hangen/Ophangen – De Definitieve Masterclass",2,"Verwarrende werkwoordparen","verwarrendeWerkwoordparen","verwarrendeWerkwoordparen"],
  ["nl-hulpwerkwoordkeuze-1","Hebben vs. Zijn in Voltooide Tijden: De Definitieve Masterclass",2,"Hulpwerkwoordkeuze","hulpwerkwoordKeuze","hulpwerkwoordKeuze"],
  ["nl-lijdendevorm-1","De Lijdende Vorm (Passief): Worden vs. Zijn – De Definitieve Masterclass",2,"Lijdende vorm","lijdendeVorm","lijdendeVorm"],
  ["nl-inversie-1","Inversie in de Hoofdzin: De V2-Regel – De Definitieve Masterclass",2,"Inversie","inversieHoofdzin","inversieHoofdzin"],
  ["nl-vraagzinnen-partikels-1","Vraagzinnen met Partikels & R-vormen: De Ultieme Masterclass",2,"Vraagzinnen","vraagzinnenMetPartikels","vraagzinnenMetPartikels"],
  ["nl-gebiedendezinnen-1","Gebiedende Zinnen: Kom hier! versus Blijft u zitten – De Ultieme Gids",2,"Gebiedende wijs","gebiedendeZinnen","gebiedendeZinnen"],
  ["nl-bijzin-sov-1","De Bijzin & SOV-Volgorde: Werkwoorden Achteraan – De Definitieve Masterclass",2,"Bijzin & Woordvolgorde","bijzinSov","bijzinSov"],
  ["nl-soortenbijzinnen-1","Soorten Bijzinnen: Tijd, Reden, Doel & Voorwaarde – De Definitieve Masterclass",2,"Soorten bijzinnen","soortenBijzinnen","soortenBijzinnen"],
  ["nl-lijdendvoorwerp-1","Het Lijdend Voorwerp: Wie/Wat + Persoonsvorm + Onderwerp? – De Definitieve Gids",2,"Lijdend voorwerp","lijdendVoorwerp","lijdendVoorwerp"],
  ["nl-meewerkendvoorwerp-1","Het Meewerkend Voorwerp: Aan Wie/Voor Wie + PV + OW + LV? – De Ultieme Tabelgids",2,"Meewerkend voorwerp","meewerkendVoorwerp","meewerkendVoorwerp"],
  ["nl-partitievest-1","De Partitieve -s: Iets Moois, Niets Bijzonders – De Ultieme Tabelgids",2,"Partitieve -s","partitieveS","partitieveS"],
  ["nl-gebiedendewijs-partikels-1","De Gebiedende Wijs met Partikels: Maar, Eens, Even – De Ultieme Tabelgids",2,"Gebiedende wijs met partikels","gebiedendeWijsPartikels","gebiedendeWijsPartikels"],
  ["nl-beleefdheidsverzoeken-zou-1","Beleefdheidsverzoeken met 'Zou(den)': De Ultieme Tabelgids",2,"Beleefdheidsverzoeken & Zou(den)","beleefdheidsverzoekenZou","beleefdheidsverzoekenZou"],
  ["nl-gevoelensenmeningen-1","Gevoelens en Meningen Verwoorden: Ik vind, ik voel, ik denk... – De Ultieme Tabelgids",2,"Gevoelens & Meningsuiting","gevoelensEnMeningen","gevoelensEnMeningen"],
  ["nl-formeeleninformeel-1","Formeel en Informeel Nederlands: U vs. Jij, Woordenschat & Toon – De Ultieme Tabelgids",2,"Formeel & Informeel","formeelEnInformeel","formeelEnInformeel"],
  ["nl-leesvaardigheid-1","Leesvaardigheid (A2): Korte Artikelen & Instructies – De Ultieme Strategie Gids",2,"Leesvaardigheid & Strategieën","leesvaardigheid","leesvaardigheid"],
  ["nl-a2-speedrun-cheatsheet-1","A2 Speedrun Cheat Sheet: Punten 46-95 in 50 Gouden Regels",2,"A2 Samenvatting & Cheat Sheet","a2SpeedrunCheatSheet","a2SpeedrunCheatSheet"],
  ["nl-afspraken-maken-1","Afspraken Maken en Verplaatsen: De Ultieme Tabelgids",2,"Afspraken & Communicatie","afsprakenMaken","afsprakenMaken"],
  ["nl-schrijfvaardigheid-brief-verslag-1","Schrijfvaardigheid: Informele Brief & Eenvoudig Verslag – De Ultieme Tabelgids",2,"Schrijfvaardigheid","schrijfvaardigheidBriefVerslag","schrijfvaardigheidBriefVerslag"],
  ["nl-spreekvaardigheid-1","Spreekvaardigheid: Een Verhaal Vertellen & Een Probleem Uitleggen – De Ultieme Tabelgids",2,"Spreekvaardigheid","spreekvaardigheid","spreekvaardigheid"],
  ["nl-afkortingen-1","Afkortingen: Initiaalwoorden, Acroniemen & Symbolen – De Ultieme Gids",3,"Spelling & Afkortingen","afkortingen","afkortingen"],
  ["nl-zinssymbolen-1","Zinssymbolen & Leestekens: De Ultieme & Meest Uitgebreide Gids",3,"Spelling & Leestekens","zinssymbolen","zinssymbolen"],
  ["nl-betrekkelijk-voornaamwoord-1","Betrekkelijk Voornaamwoord: Die, Dat, Wat, Wie & Welke – De Ultieme Gids",3,"Grammatica","betrekkelijkVoornaamwoord","betrekkelijkVoornaamwoord"],
  ["nl-vragend-voornaamwoord-1","Vragend Voornaamwoord: Wie, Wat, Welke & Wat Voor – De Ultieme Gids",3,"Grammatica","vragendVoornaamwoord","vragendVoornaamwoord"],
  ["nl-uitroepend-voornaamwoord-2","Uitroepend Voornaamwoord (Deel 2): Verdieping, Alternatieven & Nuances",3,"Grammatica","uitroependVoornaamwoord2","uitroependVoornaamwoord2"],
  ["nl-het-woord-er-1","Het Woord 'Er': De Ultieme Kameleon – De 5 Functies & Valkuilen",3,"Grammatica","hetWoordEr","hetWoordEr"],
  ["nl-voornaamwoordelijk-bijwoord-1","Voornaamwoordelijk Bijwoord: Erop, Erin, Ervan & De Splitsing – De Ultieme Gids",3,"Grammatica","voornaamwoordelijkBijwoord","voornaamwoordelijkBijwoord"],
  ["nl-vaste-voorzetselcombinaties-1","Vaste Voorzetselcombinaties: Werkwoorden & Bijvoeglijke Naamwoorden – De Ultieme Gids",3,"Grammatica","vasteVoorzetselcombinaties","vasteVoorzetselcombinaties"],
  ["nl-modale-partikels-1","Modale Partikels: Wel, Nog, Maar, Eens, Even, Toch – De Ultieme Gids",3,"Grammatica","modalePartikels","modalePartikels"],
  ["nl-partikelcombinaties-1","Combinaties van Partikels: Dan Maar, Nu Eenmaal, Wel Eens, Nog Maar",3,"Grammatica","partikelCombinaties","partikelCombinaties"],
  ["nl-focuspartikels-1","Focuspartikels: Alleen, Zelfs, Ook, Net & Pas – De Ultieme Gids",3,"Grammatica","focuspartikels","focuspartikels"],
  ["nl-voltooid-verleden-tijd-1","De Voltooid Verleden Tijd (VVT): De Ultieme Masterclass",3,"Werkwoorden & Tijden","voltooidVerledenTijd","voltooidVerledenTijd"],
  ["nl-voltooid-toekomende-tijd-1","De Voltooid Toekomende Tijd (VTTt): De Ultieme Masterclass",3,"Werkwoorden & Tijden","voltooidToekomendeTijd","voltooidToekomendeTijd"],
  ["nl-onvoltooid-verleden-toekomende-tijd-1","De Onvoltooid Verleden Toekomende Tijd (OVTt): De Absolute Masterclass",3,"Werkwoorden & Tijden","onvoltooidVerledenToekomendeTijd","onvoltooidVerledenToekomendeTijd"],
  ["nl-aanvoegende-wijs-1","De Aanvoegende Wijs (Conjunctief): Leve de Koning, Het Zij Zo",3,"Werkwoorden & Wijzen","aanvoegendeWijs","aanvoegendeWijs"],
  ["nl-progressiefconstructies-1","De Progressiefconstructies: 'Aan het' & 'Houding + te' – De Ultieme Masterclass",3,"Werkwoorden & Tijden","progressiefconstructies","progressiefconstructies"],
  ["nl-onscheidbare-werkwoorden-1","Onscheidbare Werkwoorden & Klemtoon: De Ultieme Masterclass",3,"Werkwoorden & Grammatica","onscheidbareWerkwoorden","onscheidbareWerkwoorden"],
  ["nl-wederkerende-werkwoorden-1","Wederkerende Werkwoorden: Zich Wassen & Zich Verslapen – De Ultieme Masterclass",3,"Werkwoorden & Grammatica","wederkerendeWerkwoorden","wederkerendeWerkwoorden"],
  ["nl-onpersoonlijke-werkwoorden-1","Onpersoonlijke Werkwoorden: Het Regent, Het Sneeuwt & Het Spijt Me – De Ultieme Masterclass",3,"Werkwoorden & Grammatica","onpersoonlijkeWerkwoorden","onpersoonlijkeWerkwoorden"],
  ["nl-modale-werkwoorden-1","Modale Werkwoorden: Kunnen, Moeten, Mogen, Willen, Zullen – De Ultieme Masterclass",3,"Werkwoorden & Grammatica","modaleWerkwoorden","modaleWerkwoorden"],
  ["nl-koppelwerkwoorden-1","Koppelwerkwoorden: Zijn, Worden, Blijven, Lijken, Schijnen, Blijken, Heten & Dunken – De Ultieme Masterclass",3,"Werkwoorden & Grammatica","koppelwerkwoorden","koppelwerkwoorden"],
  ["nl-werkwoordelijke-uitdrukkingen-1","Werkwoordelijke Uitdrukkingen: De Ultieme Masterclass (C1-Niveau)",3,"Woordenschat & Uitdrukkingen","werkwoordelijkeUitdrukkingen","werkwoordelijkeUitdrukkingen"],
  ["nl-hebben-zijn-zullen-1","De 'Heilige Drie-eenheid': Hebben, Zijn & Zullen – De Ultieme Masterclass",3,"Werkwoorden & Grammatica","hebbenZijnZullen","hebbenZijnZullen"],
  ["nl-sterke-werkwoorden-1","Sterke Werkwoorden: De Ultieme Klinkerverandering Gids",2,"Werkwoorden & Grammatica","sterkeWerkwoorden","sterkeWerkwoorden"],
  ["nl-passief-alle-tijden-1","Het Passief in Alle Tijden: De Ultieme Masterclass",3,"Grammatica & Zinsbouw","passiefAlleTijden","passiefAlleTijden"],
  ["nl-vooropplaatsing-1","Vooropplaatsing & Inversie: De Ultieme Gids voor Nadruk & Zinsbouw",2,"Zinsbouw & Pragmatiek","vooropplaatsing","vooropplaatsing"],
  ["nl-bijvoeglijke-bijzinnen-1","Bijvoeglijke Bijzinnen: Restrictief vs. Uitbreidend – De Ultieme Masterclass",3,"Grammatica","bijvoeglijkeBijzinnen","bijvoeglijkeBijzinnen"],
  ["nl-beknopte-bijzinnen-1","Beknopte Bijzinnen: Na... te hebben, Door... te, Zonder... te – De Ultieme Masterclass",3,"Grammatica & Zinsbouw","beknopteBijzinnen","beknopteBijzinnen"],
  ["nl-indirecte-rede-1","De Indirecte Rede: Hij Zei Dat Hij Het Zou Doen – De Ultieme Masterclass",3,"Grammatica & Zinsbouw","indirecteRede","indirecteRede"],
  ["nl-ingebedde-vragen-1","Ingebedde Vragen: 'Ik weet niet wie dat gedaan heeft' – De Ultieme Masterclass",3,"Grammatica & Zinsbouw","ingebeddeVragen","ingebeddeVragen"],
  ["nl-tangconstructie-1","De Tangconstructie: Scheidbare & Modale Werkwoorden in de Bijzin – De Ultieme Masterclass",3,"Grammatica & Zinsbouw","tangconstructie","tangconstructie"],
  ["nl-stapelwerkwoorden-1","Stapelwerkwoorden: De 'Had Moeten Kunnen Zeggen' Masterclass",3,"Grammatica & Zinsbouw","stapelwerkwoorden","stapelwerkwoorden"],
  ["nl-voorzetselvoorwerp-1","Het Voorzetselvoorwerp (VV): De Ultieme Masterclass",3,"Grammatica & Zinsontleding","voorzetselvoorwerp","voorzetselvoorwerp"],
  ["nl-naamwoordelijk-gezegde-1","Het Naamwoordelijk Gezegde: De Brug Tussen Onderwerp en Eigenschap",3,"Grammatica & Zinsontleding","naamwoordelijkGezegde","naamwoordelijkGezegde"],
  ["nl-werkwoordelijk-gezegde-1","Het Werkwoordelijk Gezegde: De Motor van de Zin – De Ultieme Masterclass",3,"Grammatica & Zinsontleding","werkwoordelijkGezegde","werkwoordelijkGezegde"],
  ["nl-bijwoordelijke-bepaling-1","De Bijwoordelijke Bepaling: Tijd, Plaats & Wijze – De Ultieme Masterclass",2,"Grammatica & Zinsontleding","bijwoordelijkeBepaling","bijwoordelijkeBepaling"],
  ["nl-congruentie-1","Congruentie (PV & OW): De Onzichtbare Draad – Enkelvoud, Meervoud & Valkuilen",3,"Grammatica & Zinsontleding","congruentie","congruentie"],
  ["nl-verbale-stijl-1","Verbale Stijl: Actief & Dynamisch Schrijven – De Ultieme Masterclass",3,"Schrijfstijl & Communicatie","verbaleStijl","verbaleStijl"],
  ["nl-stijlfouten-tautologie-pleonasme-1","Stijlfouten Herkennen: Tautologie & Pleonasme – De Ultieme Masterclass",3,"Schrijfstijl & Communicatie","stijlfoutenTautologiePleonasme","stijlfoutenTautologiePleonasme"],
  ["nl-voltooid-deelwoord-als-bn-1","Het Voltooid Deelwoord als Bijvoeglijk Naamwoord: De Ultieme Masterclass",3,"Grammatica & Woordvorming","voltooidDeelwoordAlsBijvoeglijkNaamwoord","voltooidDeelwoordAlsBijvoeglijkNaamwoord"],
  ["nl-aan-het-in-voltooide-tijden-1","'Aan het' in Voltooide Tijden (VTT & VVT): De Ultieme Masterclass",3,"Grammatica & Zinsbouw","aanHetInVoltooideTijden","aanHetInVoltooideTijden"],
  ["nl-volgorde-bijwoordelijke-bepalingen-1","De Volgorde van Bijwoordelijke Bepalingen: Tijd-Manier-Plaats",3,"Zinsbouw & Woordvolgorde","volgordeBijwoordelijkeBepalingen","volgordeBijwoordelijkeBepalingen"],
  ["nl-zinsverzachtend-maar-1","Het Zinsverzachtende 'Maar': Bagatelliseren, Geruststellen & Advies",3,"Modale Partikels & Stijl","zinsverzachtendMaar","zinsverzachtendMaar"],
  ["nl-discussies-voeren-1","Discussies Voeren: Standpunten Formuleren & Argumenten Geven – C1 Masterclass",3,"Communicatie & Stijl","discussiesVoeren","discussiesVoeren"],
  ["nl-gevoelens-en-nuance-1","Gevoelens en Nuance Uitdrukken: Van 'Goed' naar C1-Niveau",3,"Communicatie & Stijl","gevoelensEnNuance","gevoelensEnNuance"],
  ["nl-telefoneren-officiele-instanties-1","Telefoneren met Officiële Instanties: Afspraak Maken & Klagen",3,"Communicatie & Vaardigheden","telefonerenOfficieleInstanties","telefonerenOfficieleInstanties"],
  ["nl-solliciteren-1","Solliciteren: De Ultieme Masterclass voor Brief en Gesprek",3,"Communicatie & Vaardigheden","solliciteren","solliciteren"],
  ["nl-luistervaardigheid-c1-1","Luistervaardigheid : Nieuws, Discussies & Documentaires",3,"Vaardigheden & Strategieën","luistervaardigheidC1","luistervaardigheidC1"],
  ["nl-leesvaardigheid-c1-1","Leesvaardigheid C1: Teksten analyseren en begrijpen",3,"Vaardigheden & Lezen","leesvaardigheidC1","leesvaardigheidC1"],
  ["nl-schrijfvaardigheid-c1-1","Schrijfvaardigheid C1: Formele E-mail, Klacht & Samenvatting",3,"Vaardigheden & Schrijven","schrijfvaardigheidC1","schrijfvaardigheidC1"],
  ["nl-bijwoorden-frequentie-graad-1","Bijwoorden van Frequentie & Graad: Van 'altijd' tot 'nogal'",4,"Grammatica & Woordenschat","bijwoordenFrequentieGraad","bijwoordenFrequentieGraad"],
  ["nl-voltooid-verleden-toekomende-tijd-1","De Voltooid Verleden Toekomende Tijd (VVTt): De Absolute Eindbaas",4,"Werkwoorden & Tijden","voltooidVerledenToekomendeTijd","voltooidVerledenToekomendeTijd"],
];

export const nlGrammarList: GrammarLessonMeta[] = rows.map(([id, title, level, topic]) => ({ id, title, level, topic }));

export async function loadNlGrammarLesson(id: string): Promise<GrammarLesson | null> {
  const row = rows.find(([lessonId]) => lessonId === id);
  if (!row) return null;

  const [, , , , file, exportName] = row;
  const modules = import.meta.glob<Record<string, GrammarLesson>>("./*.ts");
  const loadModule = modules[`./${file}.ts`];
  if (!loadModule) return null;

  const mod = await loadModule();
  return mod[exportName] ?? null;
}